Prove that KERI-family implementations agree = goal:
  nid: 26kmlhsh
  stage-status: in-progress
  why: >-
    Implementations of CESR, KERI, ACDC and IPEX outside keripy have no way to show they are correct; a 2026-09 survey of ten Rust codebases found the same defects (for example, CESR 2.0 counters that count items where keripy counts quadlets) that a shared corpus would have caught on day one. Chose a standalone suite of fixed cases with implementation-neutral expected verdicts over adding tests to each spec or each implementation, because the interesting cases cross specs (a KEL case is also a CESR case) and test data churns at a different rate from spec prose. Tradeoff: a separate artifact to govern and keep in step with the specs, and a risk of enshrining keripy's behaviour as law, which the case-provenance and disputed-case rules exist to contain.
  children:
    The spec text is the authority, not keripy = constraint:
      nid: 9vnp6fz7
      stage-status: planned
      why: >-
        keripy generates most expected values, so without a counterweight its bugs become law and the suite certifies sameness-with-keripy rather than conformance. Chose spec authority with keripy as a provisional generator: a case whose expected value an implementation's behaviour contradicts, where the cited clause appears to say otherwise, is marked disputed, excluded from conformance tallies, and taken to the spec working group; the suite never resolves the dispute itself. Revised 2026-10-02: conflicts inside the spec's own text no longer make a case disputed (see the keyword-sentence decision). Rejected treating keripy as the reference outright. Tradeoff: disputed cases sit unresolved for as long as the working group takes.
    No case without a normative clause = decision:
      nid: 8v0gc5w4
      stage-status: planned
      why: >-
        Every assertion in a case cites the spec clause it tests and carries that clause's requirement level; MUST assertions decide conformance and SHOULD and MAY results are reported separately. Revised 2026-10-01 after the keri-review-panel (KRT-F3): the level was first attached to whole cases, which is wrong because one case checks several things at different levels (an event under its signing threshold checks a MUST not-accepted-on-arrival and a SHOULD accepted-once-completed, since the KERI spec says only that such an event SHOULD be escrowed). Corrected 2026-10-05: this node first gave out-of-order delivery as the example, but the spec's only SHOULD-escrow (KERI spec v1.0.1 L1266) covers signature and witness threshold shortfalls; out-of-order and delegation escrow have no text and are graded only in a named profile. Behaviour no clause requires (escrow kinds, error taxonomies, HTTP endpoints, the CESR 1.00 count-code table, roles without a spec) goes into a labelled non-normative profile. Rejected testing keripy behaviour wholesale because it would make the suite the de facto spec. Tradeoff: some genuinely useful interop checks are demoted to non-normative profiles, and case files are larger.
    Coarse, normative verdict vocabulary = decision:
      nid: 4mc8vyhg
      stage-status: planned
      why: >-
        KERI dispositions are decided by an ordered procedure, each step citing its clause: an intrinsic failure (encoding, SAID, schema, d not equal to i), which nothing can cure; then no verifiable controller signature, judged against key state the validator holds (MUST drop, never escrow, L1266); then a constraint of state the validator holds that forbids the event (establishment-only, do-not-delegate, non-transferable, abandoned), with the same state-held guard; then not yet acceptable relative to the trunk (threshold shortfall, prior event not seen, prior digest or pre-rotation commitment not matching the trunk, delegating seal not seen), which later events or a supersession can cure; then a conflict on the trunk (seen if rules A or B permit it to supersede, else discarded, MUST for a rotation by C1 L1823); else seen. Each message is read as seen or not, at quiescence after its own delivery and after the last, and as on the trunk or not at the end, which the adapter must drive; refinements of not-seen (pending, rejected) are graded only where a clause states them, and duplicitous is informative for a validator. Revised 2026-10-01 after the keri-review-panel (KRT-F1, KRT-F2, SPC-F3, SEC-F2, SEC-F7): the first version had four overlapping dispositions with no precedence, no value for a superseded event, no defined read point, and no stated validator perspective; cases now state a perspective. Revised 2026-10-05 after the keri-catalogue panel (KRT-F2, KRT-F5, KRT-F6, SKP-F5): the accepted/not-accepted bit became the seen and trunk readings, the state-constraint step and the intrinsic/relative split were added, and receipts get dispositions only where a clause grades them. Rejected keripy's escrow taxonomy as normative, and rejected letting keripy decide dispositions, because the suite must be able to find keripy wrong. Tradeoff: generators must compute dispositions from the procedure rather than read them off keripy.
    Published expectations are immutable = decision:
      nid: 9ppgdqn5
      stage-status: planned
      why: >-
        A case id is permanent and its expected verdict never changes; a correction is a new case id with the old case deprecated and pointing to it. This is what keeps the suite maintainable for implementers: a result recorded against suite version X never silently flips meaning, and a regression is always a code change on their side or a new case on ours. Rejected in-place correction, which is cheaper for us and turns every suite release into an unexplained diff for every implementation. Tradeoff: deprecated cases accumulate and ids are not contiguous by topic.
    Fixtures are generated, never hand-edited = decision:
      nid: 4204xnkm
      stage-status: planned
      why: >-
        Cases are produced from small declarative scenario files by generators, and CI regenerates every fixture in a pinned environment and fails on any byte difference. This makes the anti-pattern the survey and the craftsman ledger both warn about, editing an expectation to make an implementation pass, impossible to merge rather than merely forbidden. Rejected committing hand-curated fixtures, which is how cesr-test-vectors stalled with its streams section still TBD. Tradeoff: every new case needs generator support first, and the generators become code we must maintain at the bar of the runner.
    Target versions are wire versions = decision:
      nid: 9fls7thp
      stage-status: planned
      why: >-
        Case inputs are identified by the protocol versions on the wire, not by keripy release numbers, because keripy's 2.x line implements version 1.0 of most specs while emitting 2.00 codes. A profile's status comes from the maturity of the text its assertions cite, not from wire versions. Revised 2026-10-01 after the keri-review-panel (SKP-F3): the first version made every 2.x case draft and advisory, which would have demoted the count-code defect that motivated the suite even though CESR spec v1.0 states it as a MUST. Expected values from a moving implementation (keripy main ahead of a release) are draft and pinned to a commit; behaviour with no normative text, such as keripy 1.x's CESR 1.00 count codes, goes into a profile named for interoperability with keripy 1.x. Tradeoff: draft cases need regeneration as keripy moves, producing new ids when expectations change.
    Adapters speak JSON lines over stdio = decision:
      nid: 0qxf76ss
      stage-status: planned
      why: >-
        An implementation is connected through one long-lived adapter process that reads one JSON request per line and writes one JSON response per line, starting with a hello handshake that declares the adapter protocol version, the implementation's identity and commit, and its supported features. Chose stdio JSON lines over a language binding or HTTP because it works for any language, needs no port and no network, and makes an adapter a small standalone program. The runner never sends a case that needs an undeclared feature, so not-supported is decided by the declaration and an adapter cannot use it to hide a failure. Tradeoff: process startup per run and JSON escaping of binary CESR, which travels hex-encoded.
    Adapters work without upstream acceptance = decision:
      nid: 93t4d880
      stage-status: planned
      why: >-
        Each adapter builds against a released or pinned version of its implementation using only that implementation's public API, never patches it, and composes any missing entry point on top, as the survey's host layer did for devrandom. CI builds every adapter against its pin. Chose this because upstream acceptance is uncertain (each project has its own licence, governance and priorities, and may reasonably decline to host an adapter) and the suite must not depend on it. Tradeoff: adapters carry glue code that an upstream project could have exposed more cleanly, and they can lag behind implementation API changes.
    The keripy adapter stays in the suite = decision:
      nid: 5x86gnx3
      stage-status: planned
      why: >-
        keripy is both a generator and an implementation under test, so its adapter is maintained here permanently rather than offered upstream. Every result where keripy produced the expected value and keripy is also the implementation under test is flagged self-agreement, because a defect shared by generator and implementation passes silently; the flag is the witness-qualifier keripy-tests-keripy blind spot carried over. Tradeoff: we own an adapter for a moving codebase we do not control.
    Cases that disclose a vulnerability are embargoed = decision:
      nid: 5cz9hck0
      stage-status: done
      why: >-
        A case that a released implementation, keripy included, handles with a security consequence (accepts what should be rejected, retains what should be dropped, lets one input disturb the processing of others, or crashes or hangs) is a public proof of concept against it, whatever the level of the assertion. Such a case is held in a private repository, with its scenario, baseline changes and nightly results, until the project has been told privately and has had up to 90 days to ship a fix. The embargo outranks publishing a keripy-contradicting case as disputed. Revised 2026-10-01 (SEC-F5) and 2026-10-02: the trigger was first tied to failing a MUST, but a case can move to SHOULD under the inferred-obligation rule while its security consequence is unchanged; the consequence decides, not the grade. Tradeoff: the public suite lags what we know, and a private CI path must exist.
      children:
        The embargo list's location is configured, not assumed = decision:
          nid: 6q64urzv
          why: >-
            The pre-push guard (tools/embargo_guard.py) used to find the embargo list by assuming one maintainer's checkout layout, a private repository beside this one, which bound a public tool to a directory structure nobody else has and named a repository outsiders cannot see. It now takes the list from --patterns, then the KCS_EMBARGO_PATTERNS environment variable, then git config kcs.embargoPatterns (a relative value resolves against the main checkout, so every worktree agrees), and otherwise looks in the git directory at info/embargo-patterns.txt, which no commit can carry and every worktree shares. A list that was configured and cannot be read refuses the push, and so does a setting that is present but empty, because a maintainer who configured one holds embargoed material and a typo in the setting must not silently switch the check off; only an unconfigured default where nothing exists at all, the normal state for a contributor without a list, warns and lets the push through, while anything present there (a dangling symlink, a directory) must be readable or refuses. Rejected keeping the old sibling path as a fallback, which keeps the private name in the public tool. Rejected making a missing list always fatal, which would block every contributor who holds none. Tradeoff: an existing maintainer clone must set the location once, and until it does its pushes are unchecked with a warning.
    Bakobo methodology is incubation-only = decision:
      nid: 3l9vqm6q
      stage-status: done
      why: >-
        this.i, tick and the Bakobo standards block are Bakobo's practice, not the KERI Foundation's, and will be removed at the handoff (Daniel, 2026-10-01). So every rule a future maintainer needs is also written as prose under docs/, and this.i may explain why but is never the only home of a rule. Rejected keeping the reasoning only in this.i, which would leave the Foundation with rules and no rationale after removal. Tradeoff: some reasoning is stated twice and can drift; docs/ wins if they disagree after handoff.
    Apache-2.0 for test vectors, not CC-BY-4.0 = deviation:
      nid: 4g6579k6
      stage-status: done
      deviates-from: bakobo/dev standards/oss-posture.md item 1 (CC-BY-4.0 for corpora)
      scope: cases/, scenarios/ and profiles/ in this repository
      approved-by: Daniel Hardman, 2026-10-01
      why: >-
        The posture standard licenses corpora under CC-BY-4.0, but these vectors are test fixtures that implementations copy into their own Apache- and MIT-licensed test trees; a second licence on the fixtures would add attribution obligations and a licence-compatibility question to every adopter for no gain. Approved by Daniel, 2026-10-01.
    Anything but an answer is a failure = decision:
      nid: 7j5hvp2v
      stage-status: planned
      why: >-
        For every case the runner sends, a crash, a hang past the time limit, an oversized or malformed response, or an error reply fails every assertion in the case; only runner-side faults, such as failing to start the adapter, go unscored. Chosen after the keri-review-panel (SEC-F4): routing these outcomes to a neutral harness bucket would let a parser that panics or loops on hostile input escape exactly the must-reject cases built for it, the defect class the survey found. Rejected distinguishing adapter-glue exceptions from implementation exceptions, because the runner cannot see the difference and an adapter could launder failures through it. Tradeoff: a buggy adapter makes its implementation look worse than it is, which pushes adapter quality onto adapter authors.
    Adapters declare the behaviour they compose = decision:
      nid: 0eqxk4w6
      stage-status: planned
      why: >-
        When an adapter supplies logic its implementation lacks (escrow, routing, duplicity detection on top of a verification library), it lists that behaviour in the handshake's composes field, and every result record and conformance claim carries the list. Chosen after the keri-review-panel (SEC-F6): otherwise a claim such as passes every MUST case would credit a bare library with refusing duplicitous state that only the adapter refused. Rejected forbidding composition, which would exclude verification-only libraries such as devrandom's from the KERI layer entirely. Tradeoff: claims become tuples that are harder to summarize.
    IPEX transition cases wait for normative text = decision:
      nid: 69e5z0wq
      stage-status: planned
      why: >-
        The suite tests IPEX exchange messages for well-formedness, signatures and references now, and adds transcript cases classifying valid and invalid next steps only when the specs state a normative transition rule. Chosen after the keri-review-panel (KRT-F5): no clause defines which message may follow which or when a message opens a new exchange, keripy's own handlers disagree, and the first worked example would have failed a route-table-faithful implementation. Rejected deriving the state machine from keripy, which would make the suite the IPEX spec. Tradeoff: contractually protected disclosure, a core motivation, stays untested at the protocol level until the working group acts.
      children:
        IPEX messages are graded by KERI's exn rules = decision:
          nid: 6hx8msj8
          why: >-
            The ACDC spec's IPEX section declares itself non-normative (line 1797) even though it contains keyword sentences, and the separate IPEX draft is informational. The only normative text for an IPEX message is KERI v1.0.1's exchange-message rules: the exn field set (line 1197), the prior-message link p (975) and the exchange id x, which must be the SAID of an xip exchange-inception message (979). So IPEX cases are exn cases graded against those clauses through an exn.verify adapter operation, and the ACDC an IPEX grant carries is graded by acdc.verify. An implementation that starts exchanges without xip is disputed against KERI 979, not excused. Daniel agreed 2026-10-09 (Q-VQZ0). Rejected citing the non-normative IPEX section's sentences, which a section that disclaims normativity cannot support. Tradeoff: IPEX cases are thin until the working group makes IPEX normative. Revised 2026-10-09 after the acdc-design keri-review-panel (SKP-F6, SEC-F6, SEC-F7; SKP-F3 declined): every clause these cases cite is KERI's, so exchange-message cases belong to the KERI layer and the keri-1.0 profile, under KERI case ids, which gives a KERI-only implementation exn coverage and stops an acdc-1.0 result implying IPEX was tested; the IPEX layer holds only cases resting on IPEX text, of which there are none until IPEX is normative. A lone exn with an empty p and a non-empty x stays graded, because it is refused under either reading of its transaction membership: outside a transaction KERI 979 requires x to be empty, and inside one it requires an xip first. A sender-binding case, another AID's valid signature on an exn whose i is the sender, is added at MUST (KERI 1266, 1737). Revised again 2026-10-09 after the acdc-exn-cases keri-review-panel (SEC-F1, SKP-F1, KRT-F4): the exchange-message cases use a neutral route (/kcs/exchange) and an empty payload rather than IPEX routes and ACDCs, because every clause they cite is about any exchange message and a deployment with IPEX route handlers would refuse the positive pairs for IPEX reasons, leaving the refusals passable by a validator that refuses everything; the batch includes multi-key senders, numeric and weighted, whose refusals carry at least one valid sender signature, because with single-key senders the line-1266 floor alone produced every MUST and the line-1260 threshold went untested; and transaction membership is by x (979: x "universally uniquely associates" a message with its transaction), so an x naming a held xip with a p from another transaction is a 975 prior failure, while 979's x rule is cited only for an x naming a held message that is not an xip, which breaks it under either reading.
          children:
            An exchange-message reading describes a delivery = decision:
              nid: 8r78y7st
              why: >-
                exn.verify reads each exchange message twice, on its own delivery and after the last, and the protocol did not say whether a reading is about the message body or about one delivery of it. Keyed by body, a forged copy delivered after the genuine message (same body, signatures by another key) reads accepted on the genuine copy's strength, which the hostile review of PR #20 reproduced. Chose: a reading describes a delivery, the message together with the attachments it arrived with, and a second delivery of the same body is read on its own, so an adapter reports what its implementation did with that delivery's own attachments. Decided by Claude 2026-10-09 while Daniel was away (D-YNZF, resolving tick 45bv); easy to reverse before any exchange-message case exists. Rejected per-body readings, which let one valid delivery vouch for any later copy. Tradeoff: an adapter must observe per-delivery outcomes, which for keripy means wrapping its Exchanger's processing rather than reading its database alone.
    The runner has no runtime dependencies = decision:
      nid: 4fmwzdjs
      stage-status: done
      why: >-
        kcs is a Python 3.12+ package managed with uv and depends on nothing at runtime. It must install wherever an adapter author works, in whatever language, and must never pull in an implementation under test, which depending on keripy or a CESR library would do. Generators that drive keripy run in their own pinned environments. Rejected writing the runner in Rust or Go for a single static binary: the generators and the first adapter are Python anyway, and a static binary would still need a release pipeline before anyone could use it. Tradeoff: adapter authors need a Python 3.12 interpreter on the machine that runs the suite. Recorded after the 2026-10-01 design review (CON-F1); the decision was made in commit cdf9ec0 without a node.
    Adapters are checkable without running cases = decision:
      nid: 8jdu4g9r
      stage-status: planned
      why: >-
        The adapter protocol is a contract implemented outside this repo in several languages, so the suite ships JSON Schemas for every protocol message and a kcs check-adapter command that probes handshake validity, id echo, error handling, statelessness between requests and escrow quiescence; the runner also runs the statelessness probe each session and can compare a shuffled run with an ordered one. Chosen after the 2026-10-01 design review (ARC-F1, TST-F1, TST-F2): without probes, an adapter that leaks state or skips quiescence produces wrong results the runner cannot see, and the org's contract standard asks a provider to ship vectors consumers run. Rejected static request/response vectors alone, because the invariants that matter are behavioural. Tradeoff: the probes are code to maintain, and they can only detect, not prove, compliance.
    The runner contains the adapter = decision:
      nid: 09wtltes
      stage-status: planned
      why: >-
        The runner treats adapters as untrusted: response size and request time bounds, a capped line reader, process-group kill, and on POSIX memory and CPU rlimits, a scrubbed environment and a refusal to run as root; network isolation is delegated to CI jobs that hold no secrets. Chosen after the 2026-10-01 design review (SEC-F1, SEC-F2): hostile inputs are the suite's normal payload, and an allocation bomb or parser exploit must not take down the host or reach credentials. Rejected requiring a container or sandbox runtime, which would make the suite unusable on developer laptops. Tradeoff: on non-POSIX platforms the runner offers weaker containment, and the docs say so.
    Keyword sentences govern conflicts inside a spec = decision:
      nid: 740f56ur
      stage-status: done
      why: >-
        Where a sentence with an RFC 2119 keyword conflicts with a table, legend or example in the same specification, the assertion keeps the sentence's level, stays active, records the conflict in spec_conflicts and raises it with the working group. Decided by Daniel 2026-10-02 (option 2 of three) after the CESR catalogue review found the count-code rule at CESR spec line 591 contradicted by its own symbol legends. Rejected treating such conflicts as disputed, which would have excluded the founding case and about 20 others and made the suite say almost nothing until the spec is fixed. Tradeoff: the suite adopts one interpretive rule, which a spec author could contest.
    Inferred validator obligations are graded SHOULD = decision:
      nid: 20d9xrm2
      stage-status: done
      why: >-
        Where a specification states an obligation only for producers (pad bits zero, counts matching content) and the suite infers what a validator should do with a violation, the assertion is graded SHOULD with the inference recorded in inferred_from, and the gap is raised as a request that the specification state the validator rule; a stated rule later re-issues the case at its level under a new id. Decided by Daniel 2026-10-02. Rejected grading inferences MUST, which legislates on no text and invites the charge that the suite invents the specification; rejected moving them out of conformance entirely, which hides the security-relevant rejection cases. Tradeoff: a lenient parser can claim MUST conformance while failing visible SHOULDs.
    Item extents are a declared capability; summaries answer the rest = decision:
      nid: 909lzg4n
      stage-status: done
      why: >-
        Some CESR libraries accept a stream without exposing where each item starts and ends (Affinidi's parser; parts of cesrox and keripy 1.2.14), and the integrity rule forbids an adapter computing extents from counts, so before this they could only answer unsupported and gave no evidence even on must-reject cases, which need no extents. Chose a cesr.item-extents feature, required by every case with a decoded assertion and declared only by an adapter that reports items for every stream it accepts, plus an accepted summary {consumed} that a rejected assertion can be graded against. Rejected relaxing the integrity rule, which would test adapter arithmetic instead of the library, and rejected per-group-code features, which would multiply the vocabulary for gaps no case exercises. Tradeoff: an adapter with any itemization gap gives up all decoded evidence, so keriox and the keripy 1.2.14 build report decoded interop cases as not-supported.
    KERI MUST conformance means safety = decision:
      nid: 08679vxn
      stage-status: planned
      why: >-
        In the KERI layer a MUST assertion tests safety: the validator never accepts what the specification forbids and drops what it says to drop. That includes the superseding-recovery limits, because C1 (KERI spec v1.0.1 L1823) says the root KEL MUST be non-delegated, therefore A or B MUST be satisfied, or else the superseding rotation MUST be discarded, and a non-delegated KEL is its own root; so a rotation signed with a stolen current key that tries to supersede outside rules A and B is refused at MUST for every KEL. Accepting valid events (liveness) stays SHOULD, inferred, because no sentence obliges a validator to accept anything (L1780 and L1258-L1264 are preconditions). Decided by Daniel 2026-10-05 after the keri-catalogue review panel (SEC-F1, SKP-F2, SKP-F3) found the first framing graded the pre-rotation firewall and the retrograde defence at SHOULD, so a validator accepting a thief's rot1' passed every MUST. Rejected grounding refusal in L178's one-valid-KEL rule, which constrains how many KELs exist and not which event belongs on the trunk (KRT-F1). Rejected grading liveness MUST from L53, which is about trust, not acceptance (KRT-F4). Tradeoff: a validator that accepts nothing passes every MUST, which the SHOULD-reporting rule on claims exists to expose; and a conflicting interaction is outside C1's text, so its refusal is SHOULD until the spec keywords it.
    KERI dispositions are two readings, seen and trunk = decision:
      nid: 3pl4r69q
      stage-status: planned
      why: >-
        Each delivered message is reported by two readings: whether it is seen (accepted into the validator's KEL, which the spec says is permanent: first seen, always seen, never unseen, L1788), read at quiescence after its own delivery and after the last message; and whether it is on the trunk at the end. Superseded is seen and off the trunk (L1799: superseded events still remain in the KEL). Each reading is graded at the level of the clause that governs it. Chosen after the keri-catalogue review panel (KRT-F2): the single accepted bit conflated the monotone seen relation with the non-monotone trunk relation, so a recovery case had no defined final value and a conflict check could be read against either relation. Rejected keeping superseded as a third final value, which refines neither reading and cannot be graded at a different level from the seen half. Tradeoff: every adapter reports one more field per message, and an implementation without recovery must still report trunk (equal to seen).
    KERI key-state assertions are conditional = decision:
      nid: 7zdhxys3
      stage-status: planned
      why: >-
        A key-state assertion names one message and applies only if that message was finally seen: if the event was accepted, the key state is exactly this. It keeps the level of the clause that fixes the state's content, and when the condition does not hold its outcome is not-applicable, neither pass nor fail. Chosen after the keri-catalogue review panel (KRT-F3): the earlier rule graded a key-state assertion at the weakest level of the dispositions it depended on, and since every acceptance is SHOULD, the safety content of key state (a broken-commitment rotation must not change the keys) was demoted to SHOULD; an implementation that refused the rotation but applied it to its state passed every MUST. Rejected the weakest-level rule (removed from the design). Tradeoff: a validator that accepts nothing makes every key-state assertion not-applicable, which the SHOULD-reporting rule on claims exposes.
    Conformance claims report their SHOULD results = decision:
      nid: 8pz99y5p
      stage-status: planned
      why: >-
        The runner's report and printed summary carry the counts of active SHOULD assertions by outcome beside the MUST verdict, and say explicitly when any failed; a conformance claim states them too. Chosen after the keri-catalogue review panel (SKP-F3): with liveness at SHOULD and key state conditional, a validator that accepts nothing passes every KERI MUST assertion, and a bare MUST claim from it would read the same as a working validator's. Rejected raising liveness to MUST, which no keyword sentence supports, and rejected a separate liveness verdict, which would need a liveness tag the case schema does not carry. Tradeoff: the claim is longer, and the runner cannot tell a failed liveness SHOULD from a failed inferred-rejection SHOULD, so it reports both together.
    KERI case bytes come from the specification = decision:
      nid: 0mhgn74x
      stage-status: done
      why: >-
        The KERI generator builds event bodies from the specification's field rules (field order, version string L265, SAID by the CESR SAID protocol) and signs them with a standard-library Ed25519 checked against RFC 8032 and a BLAKE3 checked against its official vectors; keripy main, in a pinned side environment, cross-checks by rebuilding every untampered body byte for byte, verifying every signature and replaying each case, and a disagreement is recorded in generators/DISAGREEMENTS.md without changing an expected value. Chosen because regenerate --check runs in CI without keripy, and because bytes keripy produced could not show keripy wrong about bytes. Rejected driving keripy's builders, the first plan, for that reason. Tradeoff: the suite carries its own Ed25519 and BLAKE3, which are slow and must never be used outside generation.
    KERI expectations are checked under three keep policies = decision:
      nid: 6wvyl5ft
      stage-status: done
      why: >-
        The generator runs a model validator, the design's decision procedure steps 1 to 6, over the delivered bytes three times: keeping every not-yet-acceptable event, keeping only threshold shortfalls (the one SHOULD-escrow, L1266), and keeping nothing. Each scenario names the step it expects each message to reach, and a mismatch is a generation error; an assertion whose expected value would differ between policies is refused, because the specification lets a validator choose its policy and a MUST cannot depend on that choice. Rejected stating expected readings directly in scenarios, which would let a hand error become a published expectation. Tradeoff: some useful checks cannot be written, because they hold only under one policy; those go to the keri-escrow profile at INTEROP.
    KERI key-state MUST survives a feature gate = decision:
      nid: 2zkmdxm8
      stage-status: done
      why: >-
        In cases gated by keri.escrow or kel.recovery, the conditional key-state assertion keeps its MUST level. Its condition, that a named event was seen, can hold only for an implementation that has the feature, so the gate removes no implementation the assertion could grade, and the ungated safety half of each such scenario is a separate normative case. REVERSED 2026-10-05 by the batch-1 keri-review-panel (SEC-F1, confirmed by SKP, SPC, KRT): the exception was unnecessary and unsafe. A key-state assertion is already conditional on its event being seen, so it is not-applicable to an implementation that never reaches that state; it therefore needs no gate, and gating it instead let an adapter that declares neither keri.escrow nor kel.recovery skip a post-supersession key-state MUST entirely. The exception is removed: a case needing either feature now carries no MUST at all, and its MUSTs, key state included, move to an ungated companion case the scenario names (keri_build.py _companion_case). The rule that a MUST is never gated holds without exception. The earlier rejected alternative, demoting these to SHOULD, is moot now that they survive ungated.
    Clause coverage is measured and published = decision:
      nid: 0xd8xuzx
      why: >-
        A suite that only lists its cases cannot say where it is thin, so neither its maintainers nor an implementer reading a conformance claim can tell a well-tested clause from an untouched one. Chose a committed, rerunnable tool that enumerates every RFC 2119 keyword sentence in each pinned specification, maps every case assertion's clause and inference quotes onto those sentences, and writes a generated per-section report under docs/ that CI checks for staleness, as regenerate --check does for cases. Each sentence also carries a durable, hand-kept triage (testable by a validator, out of scope because it binds a role no adapter plays, not testable with a reason, security-bearing) in a sidecar beside the clause registry, so the report separates gaps from sentences no case could ever cover. The report counts only public cases, so it cannot reveal an embargoed one. Daniel approved a committed tool with a public report over a private one-off (2026-10-09, Q-GF8M). Rejected a one-off audit because it is stale after the next batch of cases, and rejected grading adequacy (edge and boundary depth) mechanically because it needs judgment; that grading goes in a dated narrative assessment that cites the report. Tradeoff: the triage sidecar is judgment that must be kept in step with each new spec pin, and a sentence with no triage shows as unassessed rather than being guessed.
    ACDC cases pin spec v1.0, whose wire is ACDC 2.00 = decision:
      nid: 0t3nvk73
      why: >-
        ACDC cases cite trustoverip/kswg-acdc-specification at tag v1.0 (4a543c5), the released text, as CESR and KERI are pinned on tags. That document normatively defines the ACDC 2.00 wire (version string ACDCMmmGggKKKKSSSS, line 64); for 1.x it requires only that a 2.x implementation accept the old version string (line 68). The 1.x field set, keripy 1.x's SAID computation over the expanded form, and the vcp/iss/rev registry have no normative text anywhere (the PTEL draft has no RFC 2119 keyword). So Daniel's request to build 1.0 and 2.0 cases in parallel (2026-10-09, Q-FRHD) is met by rendering each scenario twice: the 2.00 rendering in the normative profile acdc-1.0, named for the spec version as keri-1.0 is, and the 1.x rendering in the non-normative profile acdc-keripy-1x-interop, as keripy-1x-interop does for CESR 1.00. Bulk-issuance MUSTs exist only on main (f0bd097) and are issued as draft cases against that commit until a tag carries them. Main's worked examples were synced with keripy and are used only as cross-checks, never as expected values. Daniel agreed 2026-10-09 (Q-VQZ0). Rejected pinning main, which would make published cases cite an unreleased text, and rejected normative 1.x cases, which would have no clause to cite. Tradeoff: the profile named acdc-1.0 tests ACDC 2.00 wire, a naming hazard design.md must state, and SEDI's bulk issuance is tested only as draft until the next tag. Revised 2026-10-09 after the acdc-design keri-review-panel (SPC-F2, CSR-F3, KRT-F7): line 68 is read as a framing obligation, so a 1.x version string is graded only on being parsed and its body framed, and no case grades a valid verdict at MUST on a 1.x version string over a 2.00 field set, a hybrid nobody emits and keripy reads as a 1.0 body. A scenario is rendered in both profiles only when both renderings are decided at the same step with the same verdict and the same facts, so a direct-seal scenario whose 1.x form needs a vcp/iss registry gets a separately named interop case.
    ACDC verdicts are valid, invalid and incomplete; registry state is graded fact = decision:
      nid: 2pcymmuj
      why: >-
        An ACDC case gives a bundle (every KEL involved, registry events, schemas, far-node ACDCs and the presented ACDC in its compact, expanded, partial or selective form) fixed at an evaluation point, and the adapter answers valid, invalid or incomplete, decided by an ordered procedure that mirrors KERI's: intrinsic failures (version string, field order, SAIDs, most-compact SAID), schema, issuer key state, issuance commitment, registry chain, edges, else valid. The registry's verified head state is reported as facts (registry id, sequence number, said, td, ts) and graded as a conditional assertion, like KERI key state. Revoked is not a normative verdict: no clause says a revoked ACDC fails validation, and the spec gives issued and revoked only as example state values (line 2041), so the meaning of a revocation state goes into a non-normative profile. Invalid and incomplete are both not-valid at the level of the clause that failed; the distinction is informative, as design.md already treats undefined refinements. valid is a SHOULD by inference, as accepted is in KERI, because no clause obliges acceptance. Daniel agreed 2026-10-09 (Q-VQZ0). This replaces the four-verdict sketch in design.md (valid, revoked, invalid, incomplete). Rejected a normative revoked verdict, which would make the suite define revocation. Tradeoff: most ACDC safety assertions are inferred SHOULDs until the working group adds validator MUSTs, so an ACDC conformance claim reads weakly. Revised 2026-10-09 after the acdc-design keri-review-panel (KRT-F1, SPC-F1, KRT-F2, KRT-F4, KRT-F5, KRT-F6, SKP-F1, SKP-F2): edge evaluation is full-depth. The bundle holds every ACDC in the presented ACDC's provenance DAG, with their issuers' KELs and registries, bounded in node count and depth, and each edge is reported once, keyed by its near node's SAID and its label path, so multi-hop chains such as vLEI's are renderable and a diamond is unambiguous. An edge is graded on its own checks only (the far node's recomputed SAID equals n, the far node satisfies its own schema and the edge's s, the operator rules where the text says MUST), at MUST and only when the adapter reports the edge; whether an edge is reported is an inferred SHOULD. Propagation of a far node's invalidity to its edge, and of an invalid edge to the near node, is informative in acdc-1.0, because line 1114 says MAY and defers to the EGF and the NOT operator inverts it; a wholly-valid-chain verdict is graded only in the non-normative profile acdc-chain-strict. This replaces the SHOULD-inferred propagation grade and the rule that read an unreported edge through the verdict. Signature-only issuance leaves the first batch (spec issue A-G3), and every refusal scenario is paired with a positive scenario differing only in the defect, so that a fail-closed stub shows in the liveness results a claim reports.
    ACDC schema verdicts come from a declared JSON Schema subset = decision:
      nid: 6uv8mcxk
      why: >-
        Expected verdicts for schema conformance need a JSON Schema 2020-12 evaluator, and the generators are stdlib-only so that no implementation decides an expected value. The generator implements a declared subset (type, properties, required, oneOf, anyOf, const, local $ref) and refuses a scenario schema that uses anything outside it, and every schema verdict is cross-checked against keripy's validator, a disagreement being investigated rather than adopted. Daniel agreed 2026-10-09 (Q-VQZ0). Rejected depending on a third-party JSON Schema library, which would let that library's bugs become suite law and break the generators' stdlib rule. Tradeoff: a bug in the subset evaluator would become law where the cross-check agrees by coincidence, and schemas using unsupported keywords cannot be tested until the subset grows.
    ACDC levels follow a stated grading calculus = decision:
      nid: 8ky5jvcp
      why: >-
        Every ACDC and exchange-message assertion's level is derived by one calculus, written in design.md. A keyworded clause binds a validator directly only if its subject is a validator, a verifier or a verification procedure, or it states a condition for the message to be valid; a clause that defines a value (a SAID computation, an operator's effective list) binds a validator only through a validator-facing clause that requires checking that value; every other keyworded clause binds producers, and a validator's refusal of its violation is an inferred SHOULD. A refusal's level is the highest, over the derivations that independently refuse, of the lowest level along each derivation, a rule defined for AND and default edge composition only. A link resting on MAY or deferring to an EGF leaves its derivation ungraded in the normative profile, and a link resting on an analogy or only on an example makes it an inferred SHOULD. Where ACDC v1.0 leaves bytes unpinned (the version-string size and JSON form of the most compact serialization, the AGID pre-image, a schema's serialization, the code of a blinded state's ts), a refusal stays MUST only if it holds under every candidate reading, and an acceptance that depends on the choice is SHOULD with inferred_from naming it. Where a keyworded field list contradicts keripy (upd's ta against td), cases follow the text and keripy is disputed. Chosen after the acdc-design keri-review-panel (KRT-F3, SPC-F4, SPC-F1, SPC-F3, SPC-F6, CSR-F1, CSR-F2, CSR-F5, CSR-F7): the design's rule grading a refusal at the highest of its steps' levels was a bare maximum that a literal reader would use to lift a hedged propagation to MUST, and its producer-versus-validator test was unstated, so levels such as that of an expanded-form SAID refusal were set by intuition and could not be reproduced. Rejected leaving levels to each case author's judgment, which two authors apply differently. Tradeoff: fewer ACDC MUSTs, since the selective-disclosure acceptance that depends on the AGID pre-image falls to SHOULD, and the generator must record each derivation rather than only the deciding step.
    Common practice is a tested tier of its own = decision:
      nid: 6cp6vv7q
      why: >-
        Much of what deployments depend on has no normative text: the ACDC specification's IPEX section declares itself non-normative while carrying keyword sentences, the IPEX and PTEL drafts are informational, governance frameworks such as the vLEI EGF add rules, and implementations share behaviour no clause states. Triage as written could only call such sentences out of scope, which read as 'does not matter', and behaviour with no sentence was counted nowhere. Daniel chose (2026-10-09, Q-WVVX) a separate practice tier: a triage scope 'practice' for keyword sentences in sections that disclaim normativity, reported in its own coverage column; a practice catalogue for behaviour with no keyword sentence; practice cases whose assertions are level INTEROP with a 'basis' instead of a clause, in non-normative profiles that get an interoperable or not-interoperable verdict shown apart from the conformance verdict and never affecting it. A practice's basis must cite an informational text, a governance framework, or agreement between at least two independent implementations; 'keripy does it' alone is never a basis, because the spec-authority rule exists to stop the suite enshrining keripy as law. The tier starts with IPEX, which SEDI depends on and where the gap between practice and normative text is widest. Rejected leaving practice untested, which hides the part of the protocol most deployments exercise, and rejected folding it into conformance, which would make the suite the specification. Tradeoff: 'common practice' is contestable, so every practice case states its basis and a reader can disagree with it, and the tier invites scope creep, which starting with IPEX alone contains.
    The signify-ts adapter tests a pinned fork's stream parser = decision:
      nid: 2fufssce
      stage-status: in-progress
      why: >-
        Released signify-ts (0.4.0 on npm, 0.4.1 on main) is a KERIA client: it has CESR primitives and event builders but no stream parser, and leaves KEL, ACDC and exchange-message validation to KERIA, so an adapter on a release could honestly answer only cesr.encode. Daniel's fork, dhh1128/signify-ts, adds an exported CESR 1.x and 2.x stream parser in three stacked pull requests to WebOfTrust/signify-ts (#402, #403, #413). Chose an adapter pinned by commit to the top of that stack, rebased onto upstream main, implementing cesr.parse and cesr.encode only, because the parser is signify-ts's own code in signify-ts's own tree and the suite exists to test exactly such a parser before it ships. The adapter reports what parse() returns: a stream is accepted when parse() reports no error, and any reported error is a rejection whose class is the parser's own error code, including incomplete, which this protocol treats as final; nodes the parser marks unknown but frames and continues past are reported as parsed, since second-guessing the parser would make the adapter the thing tested. Item offsets are the parser's spans; raw values and indexes come from signify-ts's Matter and Indexer applied to the bytes at those spans; a genus code's version is rendered from the count the parser read. The adapter starts Node with --disable-wasm-trap-handler, because libsodium's WebAssembly cannot reserve memory under the runner's 4 GiB address-space limit otherwise. Rejected waiting for the pull requests to merge, which leaves the parser untested while it is under review, and rejected an adapter that frames streams itself on top of released primitives, which the integrity rule forbids. Tradeoff: the implementation under test is an unreleased fork written by the suite's own author, so the adapter names the fork and commit in hello and its README says so; it must be re-pinned to a signify-ts release once the parser lands, and results against the fork say nothing about released signify-ts.
