"""Measure which RFC 2119 keyword sentences of each pinned specification the public cases cite, and
publish the result under docs/coverage/.

    scripts/clause-coverage            write docs/coverage/ in the repository
    scripts/clause-coverage --out DIR  write it under DIR instead
    scripts/clause-coverage --check    generate into a temporary directory and compare, byte for
                                       byte, with what is committed; exit 1 and list every
                                       difference

Which texts: every (spec, commit) that a case's clause cites, each of which must be one of the
pins in spec_source.py. Each pin is reported separately, so a spec with two pinned versions gets
two parts in its report.

Keyword sentences: every sentence of a pinned text that contains an uppercase RFC 2119 / RFC 8174
keyword as a whole word (MUST, MUST NOT, REQUIRED, SHALL, SHALL NOT, SHOULD, SHOULD NOT,
RECOMMENDED, NOT RECOMMENDED, MAY, OPTIONAL). Its level is its strongest keyword: MUST for the
first five, SHOULD for the next four, MAY for MAY and OPTIONAL, which are permissions and are
reported apart from the obligations. REQUIRED preceded by "NOT " is not a keyword, because it
states the absence of an obligation; NOT RECOMMENDED is RFC 2119's SHOULD NOT and keeps its level. Headings and fenced code blocks are skipped. A table row is
one unit, because its cells are not sentences. A list item or block quote loses its marker and is
then split like any other line. Lines are never joined: the specification texts write each
paragraph on one line, and a quote is found by line (spec_source.find_quote).

The splitting heuristic: a sentence ends at ``.``, ``!`` or ``?``, optionally followed by closing
brackets, quotes or emphasis, when whitespace and then a character that can begin a sentence (an
uppercase letter, a digit, a backtick, an opening bracket, a quote or emphasis) follow. It does
not end inside inline code or a ``[[...]]`` reference, or after a listed abbreviation such as
"e.g.".

Mapping: each assertion's ``clause.quote``, and its ``inferred_from.quote`` if it has one, is found
in the pinned text its clause names and matched to the keyword sentences on its line that contain
it or that it contains. An assertion with an inference tests both quotes by inference; one without
tests its clause directly. A quote that matches no keyword sentence is listed in the report, not
refused. A sentence is covered when an active case cites it; disputed and other non-active cases
are listed but do not cover anything.

Triage: ``scenarios/<spec>/triage.json`` holds hand-kept judgments keyed by the exact sentence
text. A sentence whose text occurs more than once in a pinned text has a list of judgments, each
naming its ``section`` (the nearest heading's text, as the report shows it) and, when the text
also repeats within that section, its 1-based ``occurrence`` there; a single judgment may be
written as an object instead of a list of one. Each judgment must identify exactly one sentence
in every pinned text of its spec that contains the text: a repeated text without the
disambiguator it needs, a disambiguator that matches nothing, a disambiguator on a text that
does not need it, two judgments of one sentence, and an entry whose text is not a keyword
sentence of any pinned text of its spec are all refused, so stale triage fails loudly. A
sentence with no judgment is unassessed.

Exit status: 0 success; 1 --check found differences; 2 a specification text is unavailable; 3 an
input could not be interpreted (a malformed case or triage file, an unknown check type, an
unpinned commit, stale triage, an oversized report); 4 a report or its temporary copy could not be
read or written, with a code whose trailing r says retrying could help. Errors 2, 3 and 4 print a
coded message on standard error.
"""

import argparse
import errno
import json
import pathlib
import re
import sys
import tempfile
from collections import Counter
from dataclasses import dataclass, field

from . import spec_source
from .errors import GeneratorError
from .regenerate import TRIAGE_FILE

ROOT = pathlib.Path(__file__).resolve().parents[2]
REPORT_DIR = "docs/coverage"
MAX_FILE_BYTES = 1024 * 1024  # per case or triage file
# Per generated report read back from docs/coverage/. The largest, keri.md, is about 105 KB; this
# is twice the largest specification text spec_source.py will read, and a report holds at most
# that text's keyword sentences with a short row prefix each.
MAX_REPORT_BYTES = 8 * 1024 * 1024
COMMAND = "scripts/clause-coverage"
NOTICE = (f"<!-- Generated by {COMMAND} from the cases under cases/ and the triage in "
          f"scenarios/*/triage.json. Do not edit this file; rerun {COMMAND}. -->\n")

# Error codes, per Bakobo's error-code standard: the obstacle, then whether retrying could help.
# A case the measurement cannot interpret: malformed, an unknown check type or value, or a quote
# not in its pinned text.
E_CASE = "e.input.format.kcs-coverage-case.f"
# A case, triage or generated report file larger than the tool will read.
E_SIZE = "e.input.range.kcs-coverage-size.f"
# A report under docs/coverage/, or its temporary copy in --check, that could not be read or
# written; the .r variant is a failure that retrying could clear.
E_FILE = "e.env.filesystem.kcs-coverage.f"
E_FILE_TRANSIENT = "e.env.filesystem.kcs-coverage.r"
# The errnos retrying could clear, as src/keri_conformance/jsonfile.py classifies them; the
# generators use only the standard library, so the set is restated rather than imported.
TRANSIENT_ERRNOS = frozenset({errno.EIO, errno.EAGAIN, errno.EINTR, errno.EBUSY, errno.ENFILE,
                              errno.EMFILE, errno.ETIMEDOUT, errno.ESTALE})
# A clause citing a (spec, commit) that spec_source.py does not pin.
E_PIN = "e.input.range.kcs-coverage-pin.f"
# A triage file that is missing, not JSON, or not of the documented shape.
E_TRIAGE = "e.input.format.kcs-coverage-triage.f"
# A triage judgment that does not identify exactly one keyword sentence of its pinned text.
E_TRIAGE_STALE = "e.input.range.kcs-coverage-triage-sentence.f"


class CoverageError(GeneratorError):
    pass


def filesystem_error(doing: str, e: OSError) -> CoverageError:
    """A coded error for a report file operation that failed, saying whether retrying could
    help."""
    code = E_FILE_TRANSIENT if e.errno in TRANSIENT_ERRNOS else E_FILE
    return CoverageError(f"{doing}: {e}.", code)


# --- Keywords and sentences ----------------------------------------------------------------------

# REQUIRED after "NOT " states that nothing is required, so it is not a keyword.
# A keyword, with the NOT that may precede it captured in the same single pass: "NOT REQUIRED",
# with any whitespace between, is no obligation.
_KEYWORD = re.compile(r"\b(?:(NOT)\s+)?(MUST|SHALL|REQUIRED|SHOULD|RECOMMENDED|MAY|OPTIONAL)\b")
_LEVEL = {"MUST": "MUST", "SHALL": "MUST", "REQUIRED": "MUST", "SHOULD": "SHOULD",
          "RECOMMENDED": "SHOULD", "MAY": "MAY", "OPTIONAL": "MAY"}
LEVELS = ("MUST", "SHOULD", "MAY")  # strongest first
ASSERTION_LEVELS = ("MUST", "SHOULD", "MAY", "INTEROP")
OBLIGATIONS = ("MUST", "SHOULD")

# A candidate boundary: the stop, any closing punctuation, then whitespace, then a sentence start.
_BOUNDARY = re.compile(r"[.!?][)\]\"'”’*_]*(\s+)(?=[A-Z0-9`\[(\"'“‘*_])")
_PROTECTED = re.compile(r"`[^`]*`|\[\[[^\]]*\]\]")
ABBREVIATIONS = ("e.g.", "i.e.", "cf.", "vs.", "Fig.", "Sec.", "No.")
_LIST_MARKER = re.compile(r"^\s*(?:[-*+]|\d+[.)]|>)\s+")
_TABLE_SEPARATOR = re.compile(r"^\s*\|[\s:|-]*\|?\s*$")


def level_of(text: str) -> str | None:
    """The level of the strongest keyword in ``text``, or None if it has none."""
    found = {_LEVEL[m.group(2)] for m in _KEYWORD.finditer(text)
             if not (m.group(1) and m.group(2) == "REQUIRED")}
    return next((level for level in LEVELS if level in found), None)


def split_sentences(line: str, offset: int = 0) -> list[tuple[int, int]]:
    """The (start, end) spans of the sentences in ``line[offset:]``, as offsets into ``line``,
    without surrounding whitespace."""
    protected = [m.span() for m in _PROTECTED.finditer(line, offset)]
    cuts = []
    for m in _BOUNDARY.finditer(line, offset):
        stop = m.start()
        if any(a <= stop < b for a, b in protected):
            continue
        if any(line.endswith(abbr, 0, stop + 1) and not line[:stop + 1 - len(abbr)][-1:].isalnum()
               for abbr in ABBREVIATIONS):
            continue
        if line[stop - 1:stop].isupper() and not line[stop - 2:stop - 1].isalnum():
            continue  # a one-letter rule label, as in "either A. or B. MUST be satisfied"
        cuts.append((m.start(1), m.end(1)))
    spans = []
    start = offset
    for gap_start, gap_end in cuts:
        spans.append((start, gap_start))
        start = gap_end
    spans.append((start, len(line)))
    out = []
    for a, b in spans:
        chunk = line[a:b]
        if chunk.strip():
            a += len(chunk) - len(chunk.lstrip())
            b -= len(chunk) - len(chunk.rstrip())
            out.append((a, b))
    return out


@dataclass(frozen=True)
class Sentence:
    line: int  # 1-based line number in the pinned text
    start: int  # span of the sentence on its line
    end: int
    text: str
    level: str  # MUST, SHOULD or MAY
    kind: str  # prose, list or table
    section: spec_source.Heading | None  # the nearest heading before it


def keyword_sentences(text: str) -> list[Sentence]:
    """Every sentence of ``text`` that carries a keyword, in text order."""
    heads = spec_source.headings(text)
    heading_lines = {h.line for h in heads}
    out = []
    fenced = False
    for number, line in enumerate(text.splitlines(), start=1):
        if line.startswith("```"):  # the fence rule spec_source.headings uses
            fenced = not fenced
            continue
        if fenced or number in heading_lines:
            continue
        if line.lstrip().startswith("|"):
            if _TABLE_SEPARATOR.match(line):
                continue
            a = len(line) - len(line.lstrip())
            spans, kind = [(a, len(line.rstrip()))], "table"
        else:
            marker = _LIST_MARKER.match(line)
            spans = split_sentences(line, marker.end() if marker else 0)
            kind = "list" if marker else "prose"
        section = None
        for h in heads:
            if h.line > number:
                break
            section = h
        for a, b in spans:
            level = level_of(line[a:b])
            if level:
                out.append(Sentence(number, a, b, line[a:b], level, kind, section))
    return out


def map_quote(text: str, sentences: list[Sentence], quote: str) -> list[Sentence]:
    """The keyword sentences that contain ``quote`` or that ``quote`` contains, on the one line of
    ``text`` where the quote appears."""
    try:
        number = spec_source.find_quote(text, quote)
    except LookupError as e:
        raise CoverageError(str(e), E_CASE) from None
    line = text.splitlines()[number - 1]
    a = line.find(quote)
    if line.find(quote, a + 1) >= 0:
        raise CoverageError(f"Quote appears more than once on line {number} of the specification, "
                            f"so it cannot identify one sentence: {quote!r}", E_CASE)
    b = a + len(quote)
    return [s for s in sentences if s.line == number
            and ((s.start <= a and b <= s.end) or (a <= s.start and s.end <= b))]


# --- Polarity -------------------------------------------------------------------------------------

_DISPOSITIONS = {"seen": "positive", "not-seen": "negative", "rejected": "negative",
                 "pending": "negative"}


def polarity(assertion: dict, where: str) -> str:
    """Whether an assertion expects a positive outcome (something parsed, encoded, accepted or
    held) or a negative one (something refused, not accepted, or left off the trunk)."""
    check, expected = assertion.get("check"), assertion.get("expected")
    if check in ("decoded", "encoded", "key_state"):
        return "positive"
    if check == "rejected":
        return "negative"
    if check == "disposition" and isinstance(expected, str) and expected in _DISPOSITIONS:
        return _DISPOSITIONS[expected]
    if check == "trunk" and isinstance(expected, bool):
        return "positive" if expected else "negative"
    if check in ("disposition", "trunk"):
        raise CoverageError(f"{where}: a {check} of {expected!r} has no known polarity "
                            f"(disposition {expected!r}).", E_CASE)
    raise CoverageError(f"{where}: unknown check {check!r}. Clause coverage defines a polarity for "
                        f"each check type and refuses one it does not know.", E_CASE)


# --- Reading inputs --------------------------------------------------------------------------------

_CASE_ID = re.compile(r"(CESR|KERI|ACDC|IPEX)-[0-9]{4}")
_STATUSES = ("active", "draft", "disputed", "deprecated")


def _read_json(path: pathlib.Path, rel: str, code: str):
    try:
        with path.open("rb") as f:
            data = f.read(MAX_FILE_BYTES + 1)
    except OSError as e:
        raise CoverageError(f"{rel} could not be read: {e}.", code) from None
    if len(data) > MAX_FILE_BYTES:
        raise CoverageError(f"{rel} is larger than {MAX_FILE_BYTES} bytes, the most clause "
                            f"coverage reads from one file.", E_SIZE)
    try:
        return json.loads(data.decode("utf-8"))
    except (json.JSONDecodeError, UnicodeDecodeError) as e:
        raise CoverageError(f"{rel} could not be read as JSON: {e}.", code) from None


def _is_text(value) -> bool:
    return isinstance(value, str) and value != ""


def _case_problem(case, stem: str) -> str | None:
    """What is wrong with a case's shape, as far as clause coverage reads it, or None."""
    if not isinstance(case, dict):
        return "it is not an object"
    if not isinstance(case.get("id"), str) or not _CASE_ID.fullmatch(case["id"]):
        return f"{case.get('id')!r} is not a case id"
    if case["id"] != stem:
        return f"its id {case['id']} is not its file name"
    if case.get("status") not in _STATUSES:
        return f"its status {case.get('status')!r} is not one of {', '.join(_STATUSES)}"
    if not isinstance(case.get("assertions"), list) or not case["assertions"]:
        return "it has no list of assertions"
    for a in case["assertions"]:
        if not isinstance(a, dict):
            return "an assertion is not an object"
        if not _is_text(a.get("id")):
            return "an assertion id is missing"
        if not _is_text(a.get("check")):
            return f"assertion {a['id']} has no check"
        if a["check"] != "rejected" and a.get("expected") is None:
            return f"assertion {a['id']} has no expected result"
        if a.get("level") not in ASSERTION_LEVELS:
            return f"assertion {a['id']} has level {a.get('level')!r}"
        clause = a.get("clause")
        if clause is not None and not (isinstance(clause, dict) and all(
                _is_text(clause.get(k)) for k in ("spec", "commit", "quote"))):
            return f"assertion {a['id']} has a clause without a spec, commit and quote"
        inferred = a.get("inferred_from")
        if inferred is not None:
            if clause is None:
                return f"assertion {a['id']} has inferred_from without a clause"
            if not (isinstance(inferred, dict) and _is_text(inferred.get("quote"))
                    and type(inferred.get("line")) is int):
                return f"assertion {a['id']} has an inferred_from without a quote and a line"
    return None


def load_cases(root: pathlib.Path) -> list[dict]:
    """Every case under cases/, in id order, refused if clause coverage cannot read it."""
    cases = []
    for path in sorted((root / "cases").glob("*/*.json")):
        rel = path.relative_to(root).as_posix()
        case = _read_json(path, rel, E_CASE)
        problem = _case_problem(case, path.stem)
        if problem:
            raise CoverageError(f"{rel} is not a case clause coverage can read: {problem}.",
                                E_CASE)
        cases.append(case)
    return sorted(cases, key=lambda c: c["id"])


_TRIAGE_SCOPES = ("validator", "out-of-scope", "untestable")
_TRIAGE_FIELDS = {"scope", "security", "reason", "note", "section", "occurrence"}


def _judgments(value) -> list:
    """A triage entry's judgments: a list as written, or a single object as a list of one."""
    return value if isinstance(value, list) else [value]


def _judgment_problem(entry, where: str) -> str | None:
    if not isinstance(entry, dict):
        return f"{where} is not an object"
    if set(entry) - _TRIAGE_FIELDS:
        return f"{where} has the unknown fields {sorted(set(entry) - _TRIAGE_FIELDS)}"
    if entry.get("scope") not in _TRIAGE_SCOPES:
        return f"{where} has scope {entry.get('scope')!r}, not one of {_TRIAGE_SCOPES}"
    if not isinstance(entry.get("security"), bool):
        return f"{where} needs security true or false"
    if (entry["scope"] == "untestable") != ("reason" in entry):
        return f"{where} needs a reason exactly when its scope is untestable"
    if "reason" in entry and not _is_text(entry["reason"]):
        return f"{where} has an empty reason"
    if "note" in entry and not isinstance(entry["note"], str):
        return f"{where} has a note that is not text"
    if "section" in entry and not _is_text(entry["section"]):
        return f"{where} has a section that is not text"
    if "occurrence" in entry and not (type(entry["occurrence"]) is int
                                      and entry["occurrence"] >= 1):
        return f"{where} has an occurrence that is not a whole number of at least 1"
    return None


def _triage_problem(triage) -> str | None:
    if not isinstance(triage, dict):
        return "it is not an object"
    if set(triage) != {"about", "entries"}:
        extra = sorted(set(triage) - {"about", "entries"})
        return (f"it has the unknown fields {extra}" if extra
                else "it needs exactly the fields about and entries")
    if not _is_text(triage["about"]):
        return "its about field is not text"
    if not isinstance(triage["entries"], dict):
        return "its entries field is not an object keyed by sentence"
    for sentence, value in triage["entries"].items():
        where = f"the entry for {sentence!r}"
        if value == []:
            return f"{where} is an empty list"
        for entry in _judgments(value):
            problem = _judgment_problem(entry, where)
            if problem:
                return problem
    return None


def load_triage(root: pathlib.Path, label: str) -> dict:
    """The triage entries for one spec, keyed by sentence text."""
    rel = f"scenarios/{label}/{TRIAGE_FILE}"
    path = root / rel
    if not path.is_file():
        raise CoverageError(f"{rel} does not exist. Every spec a case cites needs a triage file; "
                            f"create it with an about field and an empty entries object.",
                            E_TRIAGE)
    triage = _read_json(path, rel, E_TRIAGE)
    problem = _triage_problem(triage)
    if problem:
        raise CoverageError(f"{rel} is not a triage file: {problem}.", E_TRIAGE)
    return triage["entries"]


def _section_text(s: Sentence) -> str | None:
    return s.section.text if s.section else None


def _resolve_one(label: str, sentence: str, entry: dict, same: list[Sentence]) -> Sentence:
    """The one sentence of ``same`` (every occurrence of ``sentence`` in a pinned text, in text
    order) that ``entry`` judges, or a coded error saying why it cannot be told."""
    where = f"scenarios/{label}/{TRIAGE_FILE}: {sentence!r}"
    if len(same) == 1:
        if "section" in entry or "occurrence" in entry:
            raise CoverageError(
                f"{where} occurs only once in its pinned {label} text, so its entry must not give "
                f"a section or an occurrence. Remove them.", E_TRIAGE_STALE)
        return same[0]
    if "section" not in entry:
        sections = sorted({_section_text(s) or "" for s in same})
        raise CoverageError(
            f"{where} occurs more than once in a pinned {label} text, so its entry needs a section "
            f"naming the heading it is under, one of {sections}.", E_TRIAGE_STALE)
    inside = [s for s in same if _section_text(s) == entry["section"]]
    if not inside:
        raise CoverageError(
            f"{where} occurs in no section headed {entry['section']!r} in its pinned {label} text. "
            f"The triage is stale; correct the section.", E_TRIAGE_STALE)
    if len(inside) == 1:
        if "occurrence" in entry:
            raise CoverageError(
                f"{where} occurs only once in section {entry['section']!r}, so its entry must not "
                f"give an occurrence. Remove it.", E_TRIAGE_STALE)
        return inside[0]
    if "occurrence" not in entry:
        raise CoverageError(
            f"{where} occurs {len(inside)} times in section {entry['section']!r}, so its entry "
            f"needs an occurrence from 1 to {len(inside)} saying which one it judges.",
            E_TRIAGE_STALE)
    if entry["occurrence"] > len(inside):
        raise CoverageError(
            f"{where} has occurrence {entry['occurrence']}, but it occurs only {len(inside)} times "
            f"in section {entry['section']!r}. The triage is stale; correct the occurrence.",
            E_TRIAGE_STALE)
    return inside[entry["occurrence"] - 1]


def resolve_triage(label: str, entries: dict, sentences: list[Sentence]) -> dict[Sentence, dict]:
    """The triage entry that judges each sentence of one pinned text. An entry whose sentence is
    not in this text is skipped, because another pin of the spec may hold it; one that is here
    must say which occurrence it judges exactly when there is more than one."""
    by_text: dict[str, list[Sentence]] = {}
    for s in sentences:
        by_text.setdefault(s.text, []).append(s)
    out: dict[Sentence, dict] = {}
    for sentence, value in entries.items():
        if sentence not in by_text:
            continue
        for entry in _judgments(value):
            s = _resolve_one(label, sentence, entry, by_text[sentence])
            if s in out:
                raise CoverageError(
                    f"scenarios/{label}/{TRIAGE_FILE}: two triage entries for {sentence!r} judge "
                    f"the same occurrence, on line {s.line}. Keep one.", E_TRIAGE_STALE)
            out[s] = entry
    return out


def _check_triage(label: str, entries: dict, sentence_lists: list[list[Sentence]]) -> None:
    for sentence in entries:
        if not any(s.text == sentence for found in sentence_lists for s in found):
            raise CoverageError(
                f"scenarios/{label}/{TRIAGE_FILE}: {sentence!r} is not a keyword sentence of any "
                f"pinned {label} text. The triage is stale; correct or remove the entry.",
                E_TRIAGE_STALE)
    for found in sentence_lists:
        resolve_triage(label, entries, found)


# --- Measurement ----------------------------------------------------------------------------------


@dataclass
class Row:
    sentence: Sentence
    triage: dict | None
    direct: list[str] = field(default_factory=list)  # case ids, ascending
    inferred: list[str] = field(default_factory=list)
    levels: dict[str, int] = field(default_factory=dict)  # assertions citing it, by level
    polarity: str = ""  # positive, negative, both, or "" when no active case cites it
    disputed: int = 0  # disputed cases citing it
    covered: bool = False
    statuses: dict[str, str] = field(default_factory=dict)  # case id -> status


@dataclass(frozen=True)
class Unmapped:
    line: int
    quote: str
    cited_as: str  # clause or inference
    cases: list[str]


@dataclass
class Coverage:
    pin: spec_source.Pin
    rows: list[Row]
    unmapped: list[Unmapped]


def known_pins() -> list[spec_source.Pin]:
    return [spec_source.cesr_pin(), spec_source.KERI]


def load_text(pin: spec_source.Pin) -> str:
    return spec_source.load_spec(pin=pin)


def measure(cases: list[dict], texts: dict, triage: dict) -> list[Coverage]:
    """Coverage of each pinned text. ``texts`` maps (label, commit) to (pin, text); ``triage``
    maps a label to its entries."""
    out = []
    for key in sorted(texts, key=lambda k: (k[0], texts[k][0].tag, k[1])):
        pin, text = texts[key]
        sentences = keyword_sentences(text)
        judged = resolve_triage(pin.label, triage.get(pin.label, {}), sentences)
        rows = {s: Row(s, judged.get(s)) for s in sentences}
        cites: dict[Sentence, list[tuple[dict, dict, str, str]]] = {s: [] for s in sentences}
        unmapped: dict[tuple[int, str, str], set[str]] = {}
        for case in cases:
            for a in case["assertions"]:
                where = f"{case['id']} {a['id']}"
                sign = polarity(a, where)
                clause = a.get("clause")
                if not clause or (clause["spec"], clause["commit"]) != key:
                    continue
                how = "inference" if "inferred_from" in a else "direct"
                quotes = [("clause", clause["quote"])]
                if "inferred_from" in a:
                    quotes.append(("inference", a["inferred_from"]["quote"]))
                    line = _quote_line(text, a["inferred_from"]["quote"], where)
                    if line != a["inferred_from"]["line"]:
                        raise CoverageError(
                            f"{where}: inferred_from gives line {a['inferred_from']['line']}, but "
                            f"its quote is on line {line} of the pinned {pin.name} text.", E_CASE)
                for cited_as, quote in quotes:
                    try:
                        found = map_quote(text, sentences, quote)
                    except CoverageError as e:
                        raise CoverageError(f"{where}: {e.message}", E_CASE) from None
                    if not found:
                        line = _quote_line(text, quote, where)
                        unmapped.setdefault((line, quote, cited_as), set()).add(case["id"])
                    for s in found:
                        cites[s].append((case, a, how, sign))
        for s, found in cites.items():
            _fill(rows[s], found)
        out.append(Coverage(pin, list(rows.values()), [
            Unmapped(line, quote, cited_as, sorted(ids))
            for (line, quote, cited_as), ids in sorted(
                unmapped.items(), key=lambda kv: (kv[0][0], kv[0][2] != "clause", kv[0][1]))]))
    return out


def _quote_line(text: str, quote: str, where: str) -> int:
    try:
        return spec_source.find_quote(text, quote)
    except LookupError as e:
        raise CoverageError(f"{where}: {e}", E_CASE) from None


def _fill(row: Row, cites) -> None:
    direct, inferred, signs = set(), set(), set()
    seen_assertions = set()
    levels: Counter = Counter()
    for case, a, how, sign in cites:
        (direct if how == "direct" else inferred).add(case["id"])
        row.statuses[case["id"]] = case["status"]
        if (case["id"], a["id"]) not in seen_assertions:
            seen_assertions.add((case["id"], a["id"]))
            levels[a["level"]] += 1
        if case["status"] == "active":
            signs.add(sign)
    row.direct, row.inferred = sorted(direct), sorted(inferred)
    row.levels = {level: levels[level] for level in ASSERTION_LEVELS if levels[level]}
    row.polarity = "both" if len(signs) == 2 else next(iter(signs), "")
    row.disputed = sum(status == "disputed" for status in row.statuses.values())
    row.covered = bool(signs)


# --- Rendering -------------------------------------------------------------------------------------

_TABLE_HEAD = ("| Line | Level | Triage | Direct | Inferred | Disputed | Assertions | Polarity "
               "| Cases | Sentence |\n"
               "|---:|:---|:---|---:|---:|---:|:---|:---|:---|:---|\n")
NONE = "—"


def cell(text: str) -> str:
    """``text`` as a markdown table cell: line breaks made spaces, and every pipe escaped. The text
    is markdown already, so a pipe after an odd run of backslashes is escaped as it stands; any
    other pipe gets one more backslash. Other backslashes are left alone, so the specification's
    own escapes (such as ``\\#``) render as written."""
    return re.sub(r"(?<!\\)((?:\\\\)*)\|", r"\1\\|", " ".join(text.splitlines()))


def split_row(line: str) -> list[str]:
    """The cells of a markdown table row written with ``cell``, unescaped; [] if not a row."""
    if not line.startswith("|"):
        return []
    cells = re.split(r"(?<!\\)((?:\\\\)*)\|", line.strip())
    # re.split interleaves each delimiter's even run of backslashes; rejoin it to its cell.
    joined = [cells[i] + (cells[i + 1] if i + 1 < len(cells) else "")
              for i in range(0, len(cells), 2)][1:-1]
    return [c.strip().replace("\\|", "|") for c in joined]


def _triage_cell(entry: dict | None) -> str:
    if entry is None:
        return "unassessed"
    text = entry["scope"]
    if entry["scope"] == "untestable":
        text += f": {cell(entry['reason'])}"
    if entry["security"]:
        text += ", security"
    return text


def _cases_cell(row: Row) -> str:
    out = []
    for case_id in sorted(set(row.direct) | set(row.inferred)):
        marks = [] if case_id in row.direct else ["inferred"]
        if row.statuses[case_id] != "active":
            marks.append(row.statuses[case_id])
        out.append(case_id + (f" ({', '.join(marks)})" if marks else ""))
    return ", ".join(out) or NONE


def _row_line(row: Row) -> str:
    s = row.sentence
    levels = ", ".join(f"{level} {n}" for level, n in row.levels.items()) or NONE
    cells = [str(s.line), s.level, _triage_cell(row.triage), str(len(row.direct)),
             str(len(row.inferred)), str(row.disputed), levels, row.polarity or NONE,
             _cases_cell(row), cell(s.text)]
    return "| " + " | ".join(cells) + " |\n"


def _sections(rows: list[Row], pin: spec_source.Pin) -> str:
    if not rows:
        return "No sentence of this text carries these keywords.\n\n"
    out = []
    current = object()
    for row in rows:
        heading = row.sentence.section
        if heading != current:
            if out:
                out.append("\n")
            current = heading
            if heading is None:
                out.append("#### Before the first heading\n\n")
            else:
                out.append(f"#### {heading.text}\n\n[Line {heading.line} of the specification]"
                           f"({spec_source.file_url(heading.anchor, pin)}).\n\n")
            out.append(_TABLE_HEAD)
        out.append(_row_line(row))
    return "".join(out) + "\n"


def render_spec(label: str, coverages: list[Coverage]) -> str:
    """The report for one spec: a part per pinned text, its sections in text order."""
    name = coverages[0].pin.name
    out = [NOTICE, f"\n# {name} clause coverage\n\n",
           (f"This report lists every sentence of the pinned {name} specification text that carries "
           f"an RFC 2119 keyword, with the public cases whose assertions cite it. "
           f"[README.md](README.md) explains how to read it and how it is generated.\n\n")]
    for c in coverages:
        pin = c.pin
        counts = Counter(r.sentence.level for r in c.rows)
        url = f"{pin.repo}/blob/{pin.commit}/{pin.file}"
        out.append(f"## {pin.tag}, commit {pin.commit[:12]}\n\n"
                   f"The pinned text is [{pin.file} at {pin.commit[:12]}]({url}). It has "
                   f"{len(c.rows)} keyword sentences: {counts['MUST']} MUST, {counts['SHOULD']} "
                   f"SHOULD and {counts['MAY']} MAY or OPTIONAL.\n\n")
        out.append("### Obligations (MUST and SHOULD)\n\n")
        out.append(_sections([r for r in c.rows if r.sentence.level in OBLIGATIONS], pin))
        out.append("### Permissions (MAY and OPTIONAL)\n\n")
        out.append(_sections([r for r in c.rows if r.sentence.level == "MAY"], pin))
        out.append("### Quotes that match no keyword sentence\n\n")
        if c.unmapped:
            out.append("These quotes are cited by cases but contain no keyword sentence of the "
                       "pinned text, usually because the sentence states its rule without an "
                       "uppercase keyword.\n\n| Cases | Cited as | Line | Quote |\n"
                       "|:---|:---|---:|:---|\n")
            for u in c.unmapped:
                out.append(f"| {', '.join(u.cases)} | {u.cited_as} | {u.line} | {cell(u.quote)} |\n")
            out.append("\n")
        else:
            out.append("Every quoted clause matches a keyword sentence.\n\n")
    return "".join(out).rstrip("\n") + "\n"


SUMMARY_ROWS = (
    ("MUST", "MUST sentences"),
    ("SHOULD", "SHOULD sentences"),
    ("MAY", "MAY and OPTIONAL sentences"),
    ("covered", "Obligations covered by an active case"),
    ("uncovered", "Obligations not covered"),
    ("both", "Covered obligations tested with both polarities"),
    ("validator", "Obligations triaged testable by a validator"),
    ("out-of-scope", "Obligations triaged out of scope"),
    ("untestable", "Obligations triaged untestable"),
    ("unassessed", "Obligations not yet assessed"),
    ("security covered", "Security-bearing obligations covered"),
    ("security uncovered", "Security-bearing obligations not covered"),
    ("unmapped", "Quotes that match no keyword sentence"),
)


def summarize(c: Coverage) -> dict[str, int]:
    """The summary counts for one pinned text. All but the level counts and the unmapped count
    are of obligations (MUST and SHOULD sentences) only."""
    obligations = [r for r in c.rows if r.sentence.level in OBLIGATIONS]
    scopes = Counter(r.triage["scope"] if r.triage else "unassessed" for r in obligations)
    levels = Counter(r.sentence.level for r in c.rows)
    secure = [r for r in obligations if r.triage and r.triage["security"]]
    return {
        "MUST": levels["MUST"], "SHOULD": levels["SHOULD"], "MAY": levels["MAY"],
        "covered": sum(r.covered for r in obligations),
        "uncovered": sum(not r.covered for r in obligations),
        "both": sum(r.polarity == "both" for r in obligations),
        **{scope: scopes[scope] for scope in (*_TRIAGE_SCOPES, "unassessed")},
        "security covered": sum(r.covered for r in secure),
        "security uncovered": sum(not r.covered for r in secure),
        "unmapped": len(c.unmapped),
    }


INDEX_PROSE = f"""\
This directory measures how much of each pinned specification the suite's public cases test. For every sentence that carries an uppercase RFC 2119 keyword (MUST, MUST NOT, REQUIRED, SHALL, SHALL NOT, SHOULD, SHOULD NOT, RECOMMENDED, NOT RECOMMENDED, MAY or OPTIONAL), it lists the cases whose assertions cite that sentence. It shows where the suite is thin; it does not judge whether the cases that cite a sentence test it well, which needs a reader.

Each specification has its own report, with a part for each pinned text that a case cites. Within a part, obligations (MUST and SHOULD sentences) and permissions (MAY and OPTIONAL sentences) are listed separately, each grouped under the specification's headings in text order. A sentence's level is its strongest keyword. REQUIRED preceded by NOT is not counted, because it says that nothing is required; NOT RECOMMENDED is RFC 2119's SHOULD NOT and counts as SHOULD. A table row in the specification counts as one sentence, and fenced code and headings are skipped.

Each row of a report gives:

- **Line**, **Level** and **Sentence**: where the sentence is in the pinned text, and its text.
- **Triage**: the hand-kept judgment from `scenarios/<spec>/triage.json`. `validator` means a validator can be tested on it through an adapter. `out-of-scope` means it binds a role no adapter plays, such as a controller managing its keys. `untestable` gives a reason. `security` marks a sentence with a security consequence. `unassessed` means no judgment has been recorded yet.
- **Direct** and **Inferred**: how many cases cite the sentence. An assertion cites its clause directly unless it records an inference (`inferred_from`), in which case it cites both its clause and the sentence it infers from by inference.
- **Disputed**: how many of those cases are disputed.
- **Assertions**: how many citing assertions there are at each level.
- **Polarity**: whether the active cases that cite the sentence expect a positive outcome (something parsed, encoded, accepted, or held as key state), a negative one (something rejected, not accepted, left pending, or off the trunk), or both.
- **Cases**: the case ids, marked when a case cites the sentence only by inference or is not active.

A sentence is covered when at least one active case cites it. Disputed cases are listed but cover nothing, because they are excluded from conformance results. Quotes that cases cite but that contain no keyword sentence are listed at the end of each part. The report counts only the public cases in this repository.

The reports are generated by `{COMMAND}` from the cases under `cases/` and the triage files, and CI fails if they are stale. A markdown file in this directory that does not start with the generated notice, such as a dated assessment, is written by hand and the tool leaves it alone. After adding or changing cases or triage, run `{COMMAND}` and commit the result. A triage entry is keyed by its sentence's text; when that text occurs more than once in a pinned text, each judgment also names its `section` (the heading it is under, as the report shows it) and, if the text repeats within that section too, its 1-based `occurrence` there. A judgment that does not identify exactly one sentence is refused, so triage cannot silently go stale when a specification is re-pinned.
"""


def render_index(coverages: list[Coverage]) -> str:
    """docs/coverage/README.md: how to read the reports, and a summary column per pinned text."""
    head = "| Measure |" + "".join(
        f" [{c.pin.name} {c.pin.tag}]({c.pin.label}.md) at `{c.pin.commit[:7]}` |"
        for c in coverages)
    rule = "|:---|" + "---:|" * len(coverages)
    summaries = [summarize(c) for c in coverages]
    rows = [f"| {title} |" + "".join(f" {s[key]} |" for s in summaries)
            for key, title in SUMMARY_ROWS]
    return (NOTICE + "\n# Clause coverage\n\n" + INDEX_PROSE + "\n## Summary\n\n"
            + "\n".join([head, rule, *rows]) + "\n")


# --- Generation, writing, checking ----------------------------------------------------------------


def generate(root: pathlib.Path) -> dict[str, bytes]:
    """The files under docs/coverage/ that the cases and triage determine, by repository path."""
    cases = load_cases(root)
    pins = {(p.label, p.commit): p for p in known_pins()}
    cited = set()
    for case in cases:
        for a in case["assertions"]:
            polarity(a, f"{case['id']} {a['id']}")
            clause = a.get("clause")
            if clause:
                key = (clause["spec"], clause["commit"])
                if key not in pins:
                    raise CoverageError(
                        f"{case['id']} {a['id']} cites commit {clause['commit']} of spec "
                        f"{clause['spec']!r}, which is not a pinned text in spec_source.py.", E_PIN)
                cited.add(key)
    texts = {key: (pins[key], load_text(pins[key])) for key in sorted(cited)}
    labels = sorted({label for label, _ in texts})
    triage = {label: load_triage(root, label) for label in labels}
    for path in sorted((root / "scenarios").glob(f"*/{TRIAGE_FILE}")):
        if path.parent.name not in triage:
            _check_triage(path.parent.name, load_triage(root, path.parent.name), [])
    for label in labels:
        _check_triage(label, triage[label], [keyword_sentences(text) for (lab, _), (_, text)
                                             in texts.items() if lab == label])
    coverages = measure(cases, texts, triage)
    files = {f"{REPORT_DIR}/{label}.md": render_spec(
        label, [c for c in coverages if c.pin.label == label]).encode("utf-8") for label in labels}
    files[f"{REPORT_DIR}/README.md"] = render_index(coverages).encode("utf-8")
    return files


def committed(root: pathlib.Path) -> dict[str, bytes]:
    """The committed files that generate() owns: every markdown file under docs/coverage/ that
    starts with the generated notice. A file without it, such as a dated assessment, is written
    by hand and left alone."""
    notice = NOTICE.encode("utf-8")
    out = {}
    for p in sorted((root / REPORT_DIR).glob("*.md")):
        rel = p.relative_to(root).as_posix()
        try:
            with p.open("rb") as f:
                data = f.read(len(notice))
                if data != notice:
                    continue
                data += f.read(MAX_REPORT_BYTES + 1 - len(notice))
        except OSError as e:
            raise filesystem_error(f"{rel} could not be read", e) from None
        if len(data) > MAX_REPORT_BYTES:
            raise CoverageError(f"{rel} is larger than {MAX_REPORT_BYTES} bytes, the most clause "
                                f"coverage reads from one generated report.", E_SIZE)
        out[rel] = data
    return out


def differences(want: dict[str, bytes], have: dict[str, bytes]) -> list[str]:
    lines = []
    for path in sorted(set(want) | set(have)):
        if path not in have:
            lines.append(f"missing: {path} is generated but not committed")
        elif path not in want:
            lines.append(f"extra: {path} is committed but nothing generates it")
        elif want[path] != have[path]:
            lines.append(f"differs: {path} does not match what the cases and triage generate")
    return lines


def write(root: pathlib.Path, files: dict[str, bytes]) -> None:
    """Make the owned files under ``root`` exactly ``files``."""
    for path, data in files.items():
        if len(data) > MAX_REPORT_BYTES:
            raise CoverageError(f"{path} would be larger than {MAX_REPORT_BYTES} bytes, the most "
                                f"clause coverage reads from one generated report.", E_SIZE)
    try:
        for path in sorted(set(committed(root)) - set(files)):
            (root / path).unlink()
        for path, data in files.items():
            target = root / path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(data)
    except OSError as e:
        raise filesystem_error(f"The report could not be written under {root}", e) from None


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--check", action="store_true", help="compare instead of writing")
    group.add_argument("--out", type=pathlib.Path, help="write under this directory")
    args = parser.parse_args(argv)

    diffs: list[str] = []
    try:
        files = generate(ROOT)
        if args.check:
            try:
                with tempfile.TemporaryDirectory() as tmp:
                    write(pathlib.Path(tmp), files)
                    diffs = differences(committed(pathlib.Path(tmp)), committed(ROOT))
            except OSError as e:
                raise filesystem_error("A temporary directory could not be made or removed",
                                       e) from None
        else:
            write(args.out or ROOT, files)
    except spec_source.SpecUnavailable as e:
        print(str(e), file=sys.stderr)
        return 2
    except GeneratorError as e:
        print(str(e), file=sys.stderr)
        return 4 if e.code in (E_FILE, E_FILE_TRANSIENT) else 3
    if args.check:
        if diffs:
            print("The clause coverage report differs from the committed one:")
            for line in diffs:
                print(f"  {line}")
            print(f"Run {COMMAND} and commit the result; never edit the report by hand.")
            return 1
        print(f"{len(files)} generated files match the committed ones.")
        return 0
    print(f"Wrote {len(files)} files under {args.out or ROOT}.")
    return 0
