"""Generate every CESR case and the profiles that list them, from ``scenarios/cesr/``.

``generate(root)`` returns the files it would write, as a mapping from repository-relative path
to exact bytes. ``scripts/regenerate`` writes them, or with ``--check`` compares them with what
is committed.
"""

import json
import pathlib
import re

from . import keripy1x, spec_source, tables
from .build import build_case, resolve_clauses, resolve_records
from .errors import E_CASE_ID, E_SCENARIO_JSON, E_SPEC_TABLE, GeneratorError, ScenarioError

# Failures of a case's content that the builder does not name itself: an unknown code or table
# entry, a raw value of the wrong size, a missing scenario field, a quote not in the text.
BUILD_FAILURES = (KeyError, ValueError, LookupError, TypeError)

SCENARIO_DIR = "scenarios/cesr"
CASE_DIR = "cases/cesr"
CLAUSES_FILE = "clauses.json"
CASE_ID = re.compile(r"CESR-([0-9]{4})")  # always applied with fullmatch

PROFILES = {
    "cesr-1.0": {
        "about": (
            "A profile is a named set of cases an implementation can claim: 'passes every active "
            "MUST assertion in profile P'. This file is generated by scripts/regenerate from "
            "scenarios/cesr/ and must not be edited. Fields: name; normative (true when every "
            "assertion cites a specification clause); spec (the pinned specification the "
            "assertions cite); cases (the case ids, in order). Disputed and deprecated cases are "
            "listed but excluded from conformance results by their status."
        ),
        "name": "cesr-1.0",
        "normative": True,
        "spec": {
            "name": "Composable Event Streaming Representation (CESR)",
            "repository": spec_source.SPEC_REPO,
            "tag": spec_source.SPEC_TAG,
            "commit": spec_source.SPEC_COMMIT,
        },
    },
    "cesr-strict": {
        "about": (
            "A non-normative profile: behaviour that a careful CESR parser shows but that no "
            "clause of the specification states, such as refusing a code its tables do not "
            "assign even when the code carries its own size. Every assertion is level INTEROP "
            "with a basis naming the inference it rests on, and passing it is never a "
            "conformance claim. This file is generated by scripts/regenerate from "
            "scenarios/cesr/ and must not be edited. Fields: name; normative (false); basis (what "
            "the profile's expectations rest on); cases (the case ids, in order)."
        ),
        "name": "cesr-strict",
        "normative": False,
        "basis": (
            "Inference from the CESR specification v1.0 (tag v1.0, commit "
            "037129608b9e6960858b752019ac273d40d7386c): a parser cannot know what an unassigned "
            "code means, so it should refuse it rather than skip it by its size. No clause "
            "states this."
        ),
    },
    "keripy-1x-interop": {
        "about": (
            "A non-normative profile: interoperability with keripy 1.x, not conformance. No "
            "specification defines the CESR 1.00 count-code table that keripy 1.x uses, so every "
            "assertion here rests on the named implementation's behaviour (level INTEROP, with a "
            "basis) instead of a clause. Passing it is never a conformance claim. This file is "
            "generated by scripts/regenerate from scenarios/cesr/ and must not be edited. Fields: "
            "name; normative (false); basis (the implementation and commit the expected values "
            "come from); cases (the case ids, in order)."
        ),
        "name": "keripy-1x-interop",
        "normative": False,
        "basis": {
            "implementation": "keripy",
            "version": keripy1x.KERIPY_1X_VERSION,
            "commit": keripy1x.KERIPY_1X_COMMIT,
        },
    },
}


def dumps(obj) -> bytes:
    return (json.dumps(obj, indent=2, sort_keys=True, ensure_ascii=False) + "\n").encode("utf-8")


def _load_json(path: pathlib.Path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        raise ScenarioError(f"{path.name} is not valid JSON: {e}.", E_SCENARIO_JSON) from None


def generate(root: pathlib.Path) -> dict[str, bytes]:
    scen_dir = root / SCENARIO_DIR
    spec_text = spec_source.load_spec()
    try:
        t = tables.load(spec_text)
    except BUILD_FAILURES as e:
        raise GeneratorError(f"The code tables could not be read from the pinned specification "
                             f"text: {e}.", E_SPEC_TABLE) from None
    registry = _load_json(scen_dir / CLAUSES_FILE)
    try:
        clauses = resolve_clauses(registry["clauses"], spec_text)
        conflicts = resolve_records(registry.get("conflicts", {}), spec_text, "why")
        inferences = resolve_records(registry.get("inferences", {}), spec_text, "inference")
    except BUILD_FAILURES as e:
        raise ScenarioError(f"{CLAUSES_FILE}: {e}") from None

    files: dict[str, bytes] = {}
    allowed: set[int] = set()
    members: dict[str, list[str]] = {name: [] for name in PROFILES}
    for path in sorted(scen_dir.glob("*.json")):
        if path.name == CLAUSES_FILE:
            continue
        scenario = _load_json(path)
        rel = path.relative_to(root).as_posix()
        allowed.update(gap["number"] for gap in scenario.get("id_gaps", []))
        for case in scenario["cases"]:
            case = {"profile": scenario["profile"], **case}
            case_id = case.get("id")
            if not isinstance(case_id, str) or not CASE_ID.fullmatch(case_id):
                # Checked before the id becomes part of a path, so no id can name a file
                # outside cases/cesr.
                raise ScenarioError(f"{rel}: {case_id!r} is not a case id of the form CESR-NNNN.",
                                    E_CASE_ID)
            context = case.get("context", scenario.get("context"))
            legacy = keripy1x.TABLE if context == "keripy-1.2.14" else None
            reference = keripy1x.REFERENCE if case["profile"] == "keripy-1x-interop" else None
            out = f"{CASE_DIR}/{case['id']}.json"
            if out in files:
                raise ScenarioError(f"Case id {case['id']} is used twice.")
            if case["profile"] not in members:
                raise ScenarioError(f"{case['id']}: unknown profile {case['profile']!r}.")
            try:
                built = build_case(t, rel, case, clauses, legacy, reference,
                                   scenario.get("messages"), keripy1x.TABLE, conflicts, inferences)
            except BUILD_FAILURES as e:
                raise ScenarioError(f"{rel}, {case['id']}: {type(e).__name__}: {e}") from None
            files[out] = dumps(built)
            members[case["profile"]].append(case["id"])

    numbers = sorted(int(CASE_ID.fullmatch(p.split("/")[-1][:-5]).group(1)) for p in files)
    gaps = set(range(1, numbers[-1] + 1)) - set(numbers) if numbers else set()
    if gaps - allowed:
        raise ScenarioError(f"Case ids have undocumented gaps: {sorted(gaps - allowed)}.")

    for name, profile in PROFILES.items():
        files[f"profiles/{name}.json"] = dumps({**profile, "cases": sorted(members[name])})
    return files


def committed(root: pathlib.Path) -> dict[str, bytes]:
    """The committed files that generate() owns: every case under cases/cesr and the profiles."""
    out = {p.relative_to(root).as_posix(): p.read_bytes() for p in (root / CASE_DIR).glob("*.json")}
    for name in PROFILES:
        p = root / "profiles" / f"{name}.json"
        if p.exists():
            out[f"profiles/{name}.json"] = p.read_bytes()
    return out


def differences(want: dict[str, bytes], have: dict[str, bytes]) -> list[str]:
    """Every path where the generated files ``want`` and the committed files ``have`` differ."""
    lines = []
    for path in sorted(set(want) | set(have)):
        if path not in have:
            lines.append(f"missing: {path} is generated but not committed")
        elif path not in want:
            lines.append(f"extra: {path} is committed but no scenario generates it")
        elif want[path] != have[path]:
            lines.append(f"differs: {path} does not match what its scenario generates")
    return lines


def write(root: pathlib.Path, files: dict[str, bytes]) -> None:
    """Make the generated files under ``root`` exactly ``files``: first remove every owned file
    (a case under cases/cesr, or a profile) that is no longer generated, as after a scenario is
    deleted or a case renumbered, then write each file."""
    for path in sorted(set(committed(root)) - set(files)):
        (root / path).unlink()
    for path, data in files.items():
        target = root / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
