"""Generate every CESR and KERI case and the profiles that list them, from ``scenarios/cesr/`` and
``scenarios/keri/``.

``generate(root)`` returns the files it would write, as a mapping from repository-relative path
to exact bytes. ``scripts/regenerate`` writes them, or with ``--check`` compares them with what
is committed.
"""

import json
import pathlib
import re

from . import keripy1x, spec_source, tables
from .build import build_case, resolve_clauses, resolve_records
from .errors import (
    E_CASE_ID,
    E_SCENARIO_JSON,
    E_SCENARIO_SIZE,
    E_SPEC_TABLE,
    GeneratorError,
    ScenarioError,
)
from .exn_build import build_exn_case
from .keri_build import build_keri_case

# Failures of a case's content that the builder does not name itself: an unknown code or table
# entry, a raw value of the wrong size, a missing scenario field, a quote not in the text.
BUILD_FAILURES = (KeyError, ValueError, LookupError, TypeError, AttributeError)

SCENARIO_DIR = "scenarios/cesr"
CASE_DIR = "cases/cesr"
CLAUSES_FILE = "clauses.json"
# Clause coverage's triage sidecar (clause_coverage.py) sits beside the registry; it is not a
# scenario.
TRIAGE_FILE = "triage.json"
MAX_SCENARIO_BYTES = 1024 * 1024  # per scenario or registry file
CASE_ID = re.compile(r"CESR-([0-9]{4})")  # always applied with fullmatch
KERI_SCENARIO_DIR = "scenarios/keri"
KERI_CASE_DIR = "cases/keri"
KERI_CASE_ID = re.compile(r"KERI-([0-9]{4})")  # always applied with fullmatch

PROFILES = {
    "cesr-1.0": {
        "about": (
            "A profile is a named set of cases an implementation can claim: 'passes every active "
            "MUST assertion in profile P'. This file is generated by scripts/regenerate from "
            "scenarios/cesr/ and must not be edited. Fields: name; normative (true when every "
            "assertion cites a specification clause); spec (the pinned specification the "
            "assertions cite); cases (the case ids, in order). Disputed and deprecated cases are "
            "listed but excluded from conformance results by their status."
        ),
        "name": "cesr-1.0",
        "normative": True,
        "spec": {
            "name": "Composable Event Streaming Representation (CESR)",
            "repository": spec_source.SPEC_REPO,
            "tag": spec_source.SPEC_TAG,
            "commit": spec_source.SPEC_COMMIT,
        },
    },
    "cesr-strict": {
        "about": (
            "A non-normative profile: behaviour that a careful CESR parser shows but that no "
            "clause of the specification states, such as refusing a code its tables do not "
            "assign even when the code carries its own size. Every assertion is level INTEROP "
            "with a basis naming the inference it rests on, and passing it is never a "
            "conformance claim. This file is generated by scripts/regenerate from "
            "scenarios/cesr/ and must not be edited. Fields: name; normative (false); basis (what "
            "the profile's expectations rest on); cases (the case ids, in order)."
        ),
        "name": "cesr-strict",
        "normative": False,
        "basis": (
            "Inference from the CESR specification v1.0 (tag v1.0, commit "
            "037129608b9e6960858b752019ac273d40d7386c): a parser cannot know what an unassigned "
            "code means, so it should refuse it rather than skip it by its size. No clause "
            "states this."
        ),
    },
    "keripy-1x-interop": {
        "about": (
            "A non-normative profile: interoperability with keripy 1.x, not conformance. No "
            "specification defines the CESR 1.00 count-code table that keripy 1.x uses, so every "
            "assertion here rests on the named implementation's behaviour (level INTEROP, with a "
            "basis) instead of a clause. Passing it is never a conformance claim. This file is "
            "generated by scripts/regenerate from scenarios/cesr/ and must not be edited. Fields: "
            "name; normative (false); basis (the implementation and commit the expected values "
            "come from); cases (the case ids, in order)."
        ),
        "name": "keripy-1x-interop",
        "normative": False,
        "basis": {
            "implementation": "keripy",
            "version": keripy1x.KERIPY_1X_VERSION,
            "commit": keripy1x.KERIPY_1X_COMMIT,
        },
    },
    "keri-1.0": {
        "about": (
            "A profile is a named set of cases an implementation can claim: 'passes every active "
            "MUST assertion in profile P', stated together with its SHOULD results. In this "
            "profile a MUST assertion tests safety and a SHOULD assertion mostly tests liveness "
            "(docs/design.md, KERI), so a validator that accepts nothing passes every MUST and "
            "only its SHOULD results tell it apart from a working one. This file is generated by "
            "scripts/regenerate from scenarios/keri/ and must not be edited. Fields: name; "
            "normative (true when every assertion cites a specification clause); spec (the pinned "
            "specification the assertions cite); cases (the case ids, in order). Disputed and "
            "deprecated cases are listed but excluded from conformance results by their status."
        ),
        "name": "keri-1.0",
        "normative": True,
        "spec": {
            "name": "Key Event Receipt Infrastructure (KERI)",
            "repository": spec_source.KERI.repo,
            "tag": spec_source.KERI.tag,
            "commit": spec_source.KERI.commit,
        },
    },
    "keri-escrow": {
        "about": (
            "A non-normative profile: escrow behaviour that no clause of the KERI specification "
            "states, such as keeping an event that arrives before its prior event and accepting "
            "it when the prior event arrives. Every assertion is level INTEROP with a basis naming "
            "the inference it rests on, and passing it is never a conformance claim. The safety "
            "half of each scenario, that the early event is not accepted on arrival, is a MUST "
            "case in keri-1.0. This file is generated by scripts/regenerate from scenarios/keri/ "
            "and must not be edited. Fields: name; normative (false); basis (what the profile's "
            "expectations rest on); cases (the case ids, in order)."
        ),
        "name": "keri-escrow",
        "normative": False,
        "basis": (
            "Inference from the KERI specification v1.0.1 (tag v1.0.1, commit "
            "71cb54ebb445dd9d8cb33cd29a5f50894fafc569): a validator that keeps an event it cannot "
            "accept yet, because its prior event or delegating seal has not been seen, can accept "
            "it once that arrives. The specification's only escrow obligation is for signature "
            "and witness threshold shortfalls (line 1266); no clause states this one."
        ),
    },
}


def dumps(obj) -> bytes:
    return (json.dumps(obj, indent=2, sort_keys=True, ensure_ascii=False) + "\n").encode("utf-8")


def _load_json(path: pathlib.Path):
    """A scenario or registry file, read with a bound before it is decoded."""
    try:
        with path.open("rb") as f:
            data = f.read(MAX_SCENARIO_BYTES + 1)
    except OSError as e:
        raise ScenarioError(f"{path.name} could not be read as JSON: {e}.",
                            E_SCENARIO_JSON) from None
    if len(data) > MAX_SCENARIO_BYTES:
        raise ScenarioError(f"{path.name} is larger than {MAX_SCENARIO_BYTES} bytes, the most the "
                            f"generator reads from one scenario file.", E_SCENARIO_SIZE)
    try:
        return json.loads(data.decode("utf-8"))
    except (json.JSONDecodeError, UnicodeDecodeError) as e:
        raise ScenarioError(f"{path.name} could not be read as JSON: {e}.",
                            E_SCENARIO_JSON) from None


def _scenario_shape(scenario, name: str) -> None:
    """Refuse a scenario whose top-level shape the generator cannot walk, before walking it."""
    ok = (isinstance(scenario, dict) and isinstance(scenario.get("profile"), str)
          and isinstance(scenario.get("cases"), list)
          and all(isinstance(c, dict) for c in scenario["cases"])
          and isinstance(scenario.get("id_gaps", []), list)
          and all(isinstance(g, dict) and isinstance(g.get("number"), int)
                  for g in scenario.get("id_gaps", [])))
    if not ok:
        raise ScenarioError(f"{name} is not a scenario: it needs a string \"profile\", a list of "
                            f"case objects under \"cases\", and id_gaps entries with an integer "
                            f"\"number\".")


def generate(root: pathlib.Path) -> dict[str, bytes]:
    scen_dir = root / SCENARIO_DIR
    spec_text = spec_source.load_spec()
    try:
        t = tables.load(spec_text)
    except BUILD_FAILURES as e:
        raise GeneratorError(f"The code tables could not be read from the pinned specification "
                             f"text: {e}.", E_SPEC_TABLE) from None
    registry = _load_json(scen_dir / CLAUSES_FILE)
    try:
        clauses = resolve_clauses(registry["clauses"], spec_text)
        conflicts = resolve_records(registry.get("conflicts", {}), spec_text, "why")
        inferences = resolve_records(registry.get("inferences", {}), spec_text, "inference")
    except BUILD_FAILURES as e:
        raise ScenarioError(f"{CLAUSES_FILE}: {e}") from None

    files: dict[str, bytes] = {}
    allowed: set[int] = set()
    members: dict[str, list[str]] = {name: [] for name in PROFILES}
    for path in sorted(scen_dir.glob("*.json")):
        if path.name in (CLAUSES_FILE, TRIAGE_FILE):
            continue
        scenario = _load_json(path)
        _scenario_shape(scenario, path.name)
        rel = path.relative_to(root).as_posix()
        allowed.update(gap["number"] for gap in scenario.get("id_gaps", []))
        for case in scenario["cases"]:
            case = {"profile": scenario["profile"], **case}
            case_id = case.get("id")
            if not isinstance(case_id, str) or not CASE_ID.fullmatch(case_id):
                # Checked before the id becomes part of a path, so no id can name a file
                # outside cases/cesr.
                raise ScenarioError(f"{rel}: {case_id!r} is not a case id of the form CESR-NNNN.",
                                    E_CASE_ID)
            context = case.get("context", scenario.get("context"))
            legacy = keripy1x.TABLE if context == "keripy-1.2.14" else None
            reference = keripy1x.REFERENCE if case["profile"] == "keripy-1x-interop" else None
            out = f"{CASE_DIR}/{case['id']}.json"
            if out in files:
                raise ScenarioError(f"Case id {case['id']} is used twice.")
            if case["profile"] not in members:
                raise ScenarioError(f"{case['id']}: unknown profile {case['profile']!r}.")
            try:
                built = build_case(t, rel, case, clauses, legacy, reference,
                                   scenario.get("messages"), keripy1x.TABLE, conflicts, inferences)
            except BUILD_FAILURES as e:
                raise ScenarioError(f"{rel}, {case['id']}: {type(e).__name__}: {e}") from None
            files[out] = dumps(built)
            members[case["profile"]].append(case["id"])

    numbers = sorted(int(CASE_ID.fullmatch(p.split("/")[-1][:-5]).group(1)) for p in files)
    gaps = set(range(1, numbers[-1] + 1)) - set(numbers) if numbers else set()
    if gaps - allowed:
        raise ScenarioError(f"Case ids have undocumented gaps: {sorted(gaps - allowed)}.")
    _generate_keri(root, files, members, t)

    for name, profile in PROFILES.items():
        files[f"profiles/{name}.json"] = dumps({**profile, "cases": sorted(members[name])})
    return files


def _generate_keri(root: pathlib.Path, files: dict[str, bytes],
                   members: dict[str, list[str]], t: tables.Tables) -> None:
    """Add every KERI case to ``files`` and its id to its profile in ``members``."""
    scen_dir = root / KERI_SCENARIO_DIR
    if not scen_dir.is_dir():
        return
    spec_text = spec_source.load_spec(pin=spec_source.KERI)
    registry = _load_json(scen_dir / CLAUSES_FILE)
    try:
        clauses = resolve_clauses(registry["clauses"], spec_text, spec_source.KERI)
        conflicts = resolve_records(registry.get("conflicts", {}), spec_text, "why")
        inferences = resolve_records(registry.get("inferences", {}), spec_text, "inference")
    except BUILD_FAILURES as e:
        raise ScenarioError(f"{KERI_SCENARIO_DIR}/{CLAUSES_FILE}: {e}") from None
    allowed: set[int] = set()
    numbers: list[int] = []
    for path in sorted(scen_dir.glob("*.json")):
        if path.name in (CLAUSES_FILE, TRIAGE_FILE):
            continue
        scenario = _load_json(path)
        _scenario_shape(scenario, path.name)
        rel = path.relative_to(root).as_posix()
        allowed.update(gap["number"] for gap in scenario.get("id_gaps", []))
        # Exchange-message scenarios are KERI scenarios graded through exn.verify (design, IPEX).
        builder = build_exn_case if scenario.get("operation") == "exn.verify" else build_keri_case
        for case in scenario["cases"]:
            case = {"profile": scenario["profile"], **case}
            case_id = case.get("id")
            match = KERI_CASE_ID.fullmatch(case_id) if isinstance(case_id, str) else None
            if not match:
                raise ScenarioError(f"{rel}: {case_id!r} is not a case id of the form KERI-NNNN.",
                                    E_CASE_ID)
            profile = PROFILES.get(case["profile"])
            if profile is None or not case["profile"].startswith("keri-"):
                raise ScenarioError(f"{case_id}: unknown KERI profile {case['profile']!r}.")
            try:
                built = builder(t, rel, case, clauses, inferences, conflicts,
                                profile["normative"])
            except BUILD_FAILURES as e:
                raise ScenarioError(f"{rel}, {case_id}: {type(e).__name__}: {e}") from None
            for one in built:
                match = KERI_CASE_ID.fullmatch(one["id"])
                if not match:
                    raise ScenarioError(f"{rel}: {one['id']!r} is not a case id of the form "
                                        f"KERI-NNNN.", E_CASE_ID)
                out = f"{KERI_CASE_DIR}/{one['id']}.json"
                if out in files:
                    raise ScenarioError(f"Case id {one['id']} is used twice.")
                files[out] = dumps(one)
                members[one["profile"]].append(one["id"])
                numbers.append(int(match.group(1)))
    gaps = set(range(1, max(numbers) + 1)) - set(numbers) if numbers else set()
    if gaps - allowed:
        raise ScenarioError(f"KERI case ids have undocumented gaps: {sorted(gaps - allowed)}.")


def committed(root: pathlib.Path) -> dict[str, bytes]:
    """The committed files that generate() owns: every case under cases/cesr and cases/keri, and
    the profiles."""
    out = {p.relative_to(root).as_posix(): p.read_bytes()
           for d in (CASE_DIR, KERI_CASE_DIR) for p in (root / d).glob("*.json")}
    for name in PROFILES:
        p = root / "profiles" / f"{name}.json"
        if p.exists():
            out[f"profiles/{name}.json"] = p.read_bytes()
    return out


def differences(want: dict[str, bytes], have: dict[str, bytes]) -> list[str]:
    """Every path where the generated files ``want`` and the committed files ``have`` differ."""
    lines = []
    for path in sorted(set(want) | set(have)):
        if path not in have:
            lines.append(f"missing: {path} is generated but not committed")
        elif path not in want:
            lines.append(f"extra: {path} is committed but no scenario generates it")
        elif want[path] != have[path]:
            lines.append(f"differs: {path} does not match what its scenario generates")
    return lines


def write(root: pathlib.Path, files: dict[str, bytes]) -> None:
    """Make the generated files under ``root`` exactly ``files``: first remove every owned file
    (a case under cases/cesr, or a profile) that is no longer generated, as after a scenario is
    deleted or a case renumbered, then write each file."""
    for path in sorted(set(committed(root)) - set(files)):
        (root / path).unlink()
    for path, data in files.items():
        target = root / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
