"""Generate every CESR case and the profiles that list them, from ``scenarios/cesr/``.

``generate(root)`` returns the files it would write, as a mapping from repository-relative path
to exact bytes. ``scripts/regenerate`` writes them, or with ``--check`` compares them with what
is committed.
"""

import json
import pathlib
import re

from . import keripy1x, spec_source, tables
from .build import ScenarioError, build_case, resolve_clauses

SCENARIO_DIR = "scenarios/cesr"
CASE_DIR = "cases/cesr"
CLAUSES_FILE = "clauses.json"
CASE_ID = re.compile(r"^CESR-(\d{4})$")

PROFILES = {
    "cesr-1.0": {
        "about": (
            "A profile is a named set of cases an implementation can claim: 'passes every active "
            "MUST assertion in profile P'. This file is generated by scripts/regenerate from "
            "scenarios/cesr/ and must not be edited. Fields: name; normative (true when every "
            "assertion cites a specification clause); spec (the pinned specification the "
            "assertions cite); cases (the case ids, in order). Disputed and deprecated cases are "
            "listed but excluded from conformance results by their status."
        ),
        "name": "cesr-1.0",
        "normative": True,
        "spec": {
            "name": "Composable Event Streaming Representation (CESR)",
            "repository": spec_source.SPEC_REPO,
            "tag": spec_source.SPEC_TAG,
            "commit": spec_source.SPEC_COMMIT,
        },
    },
    "keripy-1x-interop": {
        "about": (
            "A non-normative profile: interoperability with keripy 1.x, not conformance. No "
            "specification defines the CESR 1.00 count-code table that keripy 1.x uses, so every "
            "assertion here rests on the named implementation's behaviour (level INTEROP, with a "
            "basis) instead of a clause. Passing it is never a conformance claim. This file is "
            "generated by scripts/regenerate from scenarios/cesr/ and must not be edited. Fields: "
            "name; normative (false); basis (the implementation and commit the expected values "
            "come from); cases (the case ids, in order)."
        ),
        "name": "keripy-1x-interop",
        "normative": False,
        "basis": {
            "implementation": "keripy",
            "version": keripy1x.KERIPY_1X_VERSION,
            "commit": keripy1x.KERIPY_1X_COMMIT,
        },
    },
}


def dumps(obj) -> bytes:
    return (json.dumps(obj, indent=2, sort_keys=True, ensure_ascii=False) + "\n").encode("utf-8")


def generate(root: pathlib.Path) -> dict[str, bytes]:
    scen_dir = root / SCENARIO_DIR
    t = tables.load()
    spec_text = spec_source.load_spec()
    registry = json.loads((scen_dir / CLAUSES_FILE).read_text(encoding="utf-8"))
    clauses = resolve_clauses(registry["clauses"], spec_text)

    files: dict[str, bytes] = {}
    allowed: set[int] = set()
    members: dict[str, list[str]] = {name: [] for name in PROFILES}
    for path in sorted(scen_dir.glob("*.json")):
        if path.name == CLAUSES_FILE:
            continue
        scenario = json.loads(path.read_text(encoding="utf-8"))
        rel = path.relative_to(root).as_posix()
        legacy = keripy1x.TABLE if scenario.get("context") == "keripy-1.2.14" else None
        reference = keripy1x.REFERENCE if legacy is not None else None
        allowed.update(gap["number"] for gap in scenario.get("id_gaps", []))
        for case in scenario["cases"]:
            case = {"profile": scenario["profile"], **case}
            out = f"{CASE_DIR}/{case['id']}.json"
            if out in files:
                raise ScenarioError(f"Case id {case['id']} is used twice.")
            if case["profile"] not in members:
                raise ScenarioError(f"{case['id']}: unknown profile {case['profile']!r}.")
            files[out] = dumps(build_case(t, rel, case, clauses, legacy, reference))
            members[case["profile"]].append(case["id"])

    numbers = sorted(int(CASE_ID.match(p.split("/")[-1][:-5]).group(1)) for p in files)
    gaps = set(range(1, numbers[-1] + 1)) - set(numbers) if numbers else set()
    if gaps - allowed:
        raise ScenarioError(f"Case ids have undocumented gaps: {sorted(gaps - allowed)}.")

    for name, profile in PROFILES.items():
        files[f"profiles/{name}.json"] = dumps({**profile, "cases": sorted(members[name])})
    return files


def committed(root: pathlib.Path) -> dict[str, bytes]:
    """The committed files that generate() owns: every case under cases/cesr and the profiles."""
    out = {p.relative_to(root).as_posix(): p.read_bytes() for p in (root / CASE_DIR).glob("*.json")}
    for name in PROFILES:
        p = root / "profiles" / f"{name}.json"
        if p.exists():
            out[f"profiles/{name}.json"] = p.read_bytes()
    return out


def differences(want: dict[str, bytes], have: dict[str, bytes]) -> list[str]:
    """Every path where the generated files ``want`` and the committed files ``have`` differ."""
    lines = []
    for path in sorted(set(want) | set(have)):
        if path not in have:
            lines.append(f"missing: {path} is generated but not committed")
        elif path not in want:
            lines.append(f"extra: {path} is committed but no scenario generates it")
        elif want[path] != have[path]:
            lines.append(f"differs: {path} does not match what its scenario generates")
    return lines


def write(root: pathlib.Path, files: dict[str, bytes]) -> None:
    for path, data in files.items():
        target = root / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
